### ISSUE TITLE
context management/with and sessions

### ISSUE THREAD

**Issue by charterchap** [ni/nimi-python#1032]
Suppose I'm using nidcpower and I want pwr_up and pwr_down methods.
```
# which is preferred? and why?
# option 1
def pwr_up():
    with nidcpower.Session(resource_name='PXI1Slot4', channels='0,1') as session:
        with session.initiate():
            session.channels[str('0,1')].output_enabled = True
def pwr_dwn():
    with nidcpower.Session(resource_name='PXI1Slot4', channels='0,1') as session:
        with session.initiate():
            session.channels[str('0,1')].output_enabled = False

# option 2
session = nidcpower.Session(resource_name='PXI1Slot4', channels='0,1', reset=True)
def pwr_up():
    with session.initiate():
        session.channels[str('0,1')].output_enabled = True
def pwr_dwn():
    with session.initiate():
        session.channels[str('0,1')].output_enabled = False

```

**Comment by marcoskirsch** [comment]
Hello,

In `option 1` you are opening and closing a session to your device on every call. This is not a lightweight operation, and everytime you do this, all the properties start out in their default state. So when you `initiate()` the device will be configured using the default values of the properties. This is most likely not what you want.

In `option 2` you "only" `initiate()` every time (and when the context manager `__exit()__`s then the `abort()` is called. The `output_enabled` property is "on-the-fly" which means it can be configured while running. You could instead:
* Create the `Session`.
* Configure voltage/current and the initial state of `output_enabled` plus whatever else is needed.
* `initiate()` which leave the `Session` in the "running" state.
Then in your functions, you just need to set `output_enabled`.

Hope this is helpful.
