### ISSUE TITLE
nimi-bot links are wrong

### ISSUE THREAD

**Issue by marcoskirsch** [ni/nimi-python#1040]
# Description of issue

For PRs, we automatically run a series of system tests on a VM internal to NI called "nimi-bot". The machine was moved which annoyingly changed its URL

Instead of:
http://nimipy-jenkins.ni.corp.natinst.com:8080/

it should be:
http://nimipy-jenkins.natinst.corp.natinst.com:8080/

Alternatively, we could work with IT to give it a fixed URL.

Note that the system, 

# Steps to reproduce issue

From within NI's intranet go to http://nimipy-jenkins.natinst.corp.natinst.com:8080/

**Comment by texasaggie97** [comment]
Fixed the configuration of nimi-bot to use the correct URL.
