### ISSUE TITLE
niscope.DriverError not found

### ISSUE THREAD

**Issue by omejia10** [ni/nimi-python#1060]
Using niscope.DriverError gives error `NameError: name 'DriverError' is not defined`
this is confusing since documentation shows support [here](https://nimi-python.readthedocs.io/en/master/niscope/errors.html)

  OS:
    Name:      Windows
    Version:   10.0.16299
    Bits:      64
Driver:
    Name:      NI-SCOPE
    Version:   19.1.0.16388
Module:
    Name:      niscope
    Version:   1.1.2
Python:
    Version:   3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 19:29:22) [MSC v.1916 32 bit (Intel)]
    Bits:      32
    Is_Venv:   True
    Installed Packages:
        zipp==0.6.0
        wcwidth==0.1.7
        six==1.12.0
        setuptools==40.8.0
        pytest==5.0.1
        pyparsing==2.4.2
        py==1.8.0
        pluggy==0.13.0
        pip==19.0.3
        packaging==19.2
        niscope==1.1.2
        more-itertools==7.2.0
        importlib-metadata==0.23
        colorama==0.4.1
        attrs==19.2.0
        atomicwrites==1.3.0

 

    1. using pytest try to run the following code:
```
import pytest
import niscope
from pytest import raises

def test_abort_then_fetch(resourceName):
    # from niscope.errors import DriverError
    with niscope.Session(resourceName) as session:
        session.min_sample_rate = session.max_real_time_sampling_rate
        session.channels["0"].channel_enabled = True
        session.trigger_type = niscope.TriggerType.SOFTWARE
        session.commit()
        with session.initiate():
            with raises(niscope.DriverError):
                session.channels[0].fetch(timeout=0.5)
            session.abort()
```

    2. see error
    3. uncomment line  # from niscope.errors import DriverError
    4. see error doesn't happen anymore

**Comment by texasaggie97** [comment]
I am able to reproduce this. There are a couple of ways to work around this depending on your needs.

If you don't care which type of listed exception you get, you can look for the base error exception, `niscope.Error`.

If you do need to explicitly look for `DriverError` you can `import niscope.errors` and then check for `niscope.errors.DriverError`

At this point I am not sure if we will fix this by making all the exceptions available as implied by the documentation or if we will update the documentation to explicitly say you need to import and use the errors from `<driver>.errors`
