### ISSUE TITLE
Many enum types are missing from nidigital API

### ISSUE THREAD

**Issue by sbethur** [ni/nimi-python#1064]
* Description of issue

Many enum types are missing from nidigital API. Compare enums.py and enums defined in nidigital C header to determine the missing enum types.

**Comment by texasaggie97** [comment]
All enums (`NIDIGITAL_VAL_*`) in the header are in the metadata.

If an enum is not used anywhere (parameter type or attribute type) then it will not be in the generated code. The fix for this issue is to set `'enum'` in the metadata appropriately.

**Comment by sbethur** [comment]
Ah, gotcha. We have an [issue](https://github.com/ni/nimi-python/issues/1066) open for updating methods and properties to use enums. Looks like there's nothing to be done for this issue, I'll close it.
