### ISSUE TITLE
write_source_waveform_site_unique_u32 missing in nidigital API

### ISSUE THREAD

**Issue by sbethur** [ni/nimi-python#1069]
# Description of issue

write_source_waveform_site_unique_u32 missing in nidigital API.
Corresponding method in C header is `niDigital_WriteSourceWaveformSiteUniqueU32`

> Is this issue only to enable this method or to make a "fancy" version of it?

We need a fancy version.

`write_source_waveform_site_unique_u32` method is closely related to already implemented `write_source_waveform_broadcast_u32`.

`write_source_waveform_broadcast_u32` needs to be updated to take in only `waveform_name` and `waveform_data`. `waveform_data` can be of type list or array.array or numpy.ndarray. This work is tracked [here](https://github.com/ni/nimi-python/issues/1070).

Parameters for `write_source_waveform_site_unique_u32` should be:

1. `site_list` of type str
2. `waveform_name` of type str
3. `waveform_data` of type "2D array" of ViUInt32. I think we should accept:
    - numpy.ndarray
    - list of lists or array.arrays

We should also validate that size of all arrays inside `waveform_data` is same.

Method should not return anything.

**Comment by marcoskirsch** [comment]
@sbethur to split this up into two issues.

**Comment by texasaggie97** [comment]
@sbethur, Is this issue only to enable this method or to make a "fancy" version of it?

If fancy, what should the parameter list look like, and what should the output be and in what format?

**Comment by sbethur** [comment]
> If fancy, what should the parameter list look like, and what should the output be and in what format?

Updated issue description.

**Comment by sbethur** [comment]
Rethinking the types for this method.. we should consider `site_list` and `waveform_data` into a dict or namedtuple. It should consistent with what's used in `fetch_capture_waveform`.
