### ISSUE TITLE
Improve usability of nidigital History RAM API

### ISSUE THREAD

**Issue by sbethur** [ni/nimi-python#1071]
* Description of issue
Currently, History RAM (HRAM) configuration can be done via a set of properties or using a set of `configure_history_ram_xyz` methods. Fetching of HRAM samples is done by calling `get_history_ram_sample_count` to get the number of samples and then calling `fetch_history_ram_cycle_xyz` in a loop.

Usability can be improved by getting rid of `configure_history_ram_xyz` methods and providing a multi-sample fetch API.

**Comment by marcoskirsch** [comment]
Will likely require “fancy functions” (hand coded wrappers) to fix.
