### ISSUE TITLE
Need nidigital examples

### ISSUE THREAD

**Issue by sbethur** [ni/nimi-python#1073]
* Description of issue

Need nidigital examples

**Comment by rriola** [comment]
Hi nimi-python Team,

Are there any updates on this? 
We'll be looking forward to your most favorable response, and Happy New Year!

**Comment by sbethur** [comment]
We are currently finalizing [nidigital API](https://github.com/ni/nimi-python/milestone/20). After that's done, we'll be adding examples, which is tied to [nidigital 1.0](https://github.com/ni/nimi-python/milestone/22) milestone.

As we're working on the API, our goal is to make it as user-friendly and "Pythonic" as possible. As a result, we are envisioning adding examples only for specific parts of the API, where they are warranted.

For now, you can refer to the [system tests](https://github.com/ni/nimi-python/tree/master/src/nidigital/system_tests) we've written and continue to write. Something like the [fetch_capture_waveform test](https://github.com/ni/nimi-python/blob/3e5b0e12c0d6070c36a4c142e7544cb84095f365/src/nidigital/system_tests/test_system_nidigital.py#L182) performs most of the core digital operations (load pattern, load pin map and other files; configure source and capture waveforms; and burst a pattern). It would be awesome if you can start using the API and provide feedback on API usability and need for examples.
