### ISSUE TITLE
nidigital fetch_capture_waveform_u32 returns empty list

### ISSUE THREAD

**Issue by alexp-st** [ni/nimi-python#1074]
* Description of issue

In nidigital driver, calling fetch_capture_waveform_u32 method after executing a pattern with digital capture returns an empty list.

I managed to fix this issue by modifying session.py line 3058 as follow:
<- data_buffer_size_ctype = _visatype.ViInt32(error_code)  # case S180
-> data_buffer_size_ctype = _visatype.ViInt32(actual_num_waveforms_ctype.value * actual_samples_per_waveform_ctype.value)

* `python -c "import niscope; niscope.print_diagnostic_information()"` output (replace `niscope` with appropriate package name)

nidigital version: 0.1.0

* Steps to reproduce issue

    1. Step 1: Initialise nidigital session
    2. Step 2: load pinmap, spec, levels, timings, pattern, digital capture
    3. Step3: Execute pattern with digital capture (session.burst_pattern)
    4. Step4: Get digital capture (fetch_capture_waveform_u32)

**Comment by alexp-st** [comment]
If my understanding of the driver if correct, this issue should be considered as a BUG.
data_buffer_size_ctype is not correctly updated before the 2nd call to niDigital_FetchCaptureWaveformU32

**Comment by sbethur** [comment]
@alexp-st , Yes, it is a bug. There is [PR](https://github.com/ni/nimi-python/pull/1096) in review to fix this API entry point.
