### ISSUE TITLE
fetch_capture_waveform_u32 missing in nidigital API

### ISSUE THREAD

**Issue by sbethur** [ni/nimi-python#1076]
# Description of issue

fetch_capture_waveform_u32 missing in nidigital API.
Corresponding method in C header is `niDigital_FetchCaptureWaveformU32`

> @sbethur, Is this issue only to enable this method or to make a "fancy" version of it?

There should be a fancy version.

Parameters should be:

1. `site_list` of type str
2. `waveform_name` of type str
3. `samples_to_read` of type int
4. `timeout` of type float or datetime.timedelta

Return value should be "2D array" of VIUInt32. To be consistent with similar fetch method in niscope API, we can make the actual type be a list of memoryview of array.array.

**Comment by texasaggie97** [comment]
@sbethur, Is this issue only to enable this method or to make a "fancy" version of it?

If fancy, what should the parameter list look like, and what should the output be and in what format?

**Comment by sbethur** [comment]
> If fancy, what should the parameter list look like, and what should the output be and in what format?

Updated issue description.
