### ISSUE TITLE
Tooling required to allow users to easily find support files for nidigital examples

### ISSUE THREAD

**Issue by sbethur** [ni/nimi-python#1088]
### Description of issue

nidigital examples require support files (pattern files, pinmap file etc.). Examples are not installed on the system when a nimi-python API is installed, rather users find the examples on [ReadTheDocs](https://nimi-python.readthedocs.io/en/master/nidcpower/examples.html).

Example page on ReadTheDocs should point the users to the support files location and explain where they should copy the support files, before running the example.

**Comment by texasaggie97** [comment]
I created two solutions for this because I couldn't decide which I liked better.
#1162 - I think this is a better solution for the user, but the solution is complicated and messy with obscure make content
#1163 - Maybe less convenient for the user but the solution is clean and compact

**Comment by sbethur** [comment]
My vote is for per-driver zip files. Usually, users writing test programs will target one or two APIs at a time.
