### ISSUE TITLE
python 3.8 can't load NI-SCOPE runtime

### ISSUE THREAD

**Issue by omejia10** [ni/nimi-python#1091]
* Description of issue

    After doing a clean install of python 3.8 from python.org/downloads/  niScope alwyas throws error 

`niscope.errors.DriverNotInstalledError: The NI-SCOPE runtime could not be loaded. Make sure it is installed and its bitness matches that of your Python interpreter. Please visit http://www.ni.com/downloads/drivers/ to download and install it.`

looking into the error I see that there's always an issue when trying to load the library, trying known fixes like adding the path to environment variable, or adding the path to PYTHONPATH don't seem to work.  Not even placing the niScope_64.dll in the same directory as the application. 

changing _library_singleton.py  `_library_info`'s `name` parameter to be an absolute path fixes the issue.

* `python -c "import niscope; niscope.print_diagnostic_information()"`  output
    
```
    OS:
    Name:      Windows
    Version:   10.0.18362
    Bits:      64
Driver:
    Name:      NI-SCOPE
    Version:   19.1.0.49152
Module:
    Name:      niscope
    Version:   1.1.3
Python:
    Version:   3.8.0 (tags/v3.8.0:fa919fd, Oct 14 2019, 19:37:50) [MSC v.1916 64 bit (AMD64)]
    Bits:      64
    Is_Venv:   True
    Installed Packages:
        wcwidth==0.1.7
        six==1.12.0
        setuptools==41.2.0
        pytest==5.2.2
        pyparsing==2.4.2
        py==1.8.0
        pluggy==0.13.0
        pip==19.2.3
        packaging==19.2
        nitclk==0.1.0
        niscope==1.1.3
        more-itertools==7.2.0
        colorama==0.4.1
        attrs==19.3.0
        atomicwrites==1.3.0
```

* Steps to reproduce issue

    1. Install python 3.8.
    2. Install niScope 19.1 driver.
    3. Run example.

* Additional steps: this raises "FileNotFoundError: Could not find module 'niscope_64.dll'. Try using the full path with constructor syntax." which eventually turns into  errors.DriverNotInstalledError()

snipet
```
import ctypes
ctypes_library = ctypes.CDLL('niscope_64.dll')
```
    1. Install python 3.8.
    2. Install niScope 19.1 driver.
    3. Run snippet.

**Comment by texasaggie97** [comment]
I found this in the 3.8 version of the ctypes documents:
> The winmode parameter is used on Windows to specify how the library is loaded (since mode is ignored). It takes any value that is valid for the Win32 API LoadLibraryEx flags parameter. When omitted, the default is to use the flags that result in the most secure DLL load to avoiding issues such as DLL hijacking. Passing the full path to the DLL is the safest way to ensure the correct library and dependencies are loaded
> Changed in version 3.8: Added winmode parameter.

So this is a new parameter. We can use `ctypes.util.find_library()` to get the full path and then pass that into `ctypes.CDLL()`
