### ISSUE TITLE
Make nidigital methods that accept pinList argument easier to use

### ISSUE THREAD

**Issue by sbethur** [ni/nimi-python#1093]
### Description of issue

Many methods in nidigital API accept `channel_list` parameter. Here's the description of that parameter in C API reference:

> List of channel names or list of pins. Do not pass a mix of channel names and pin names. An empty string denotes all digital pattern instrument channels. Pin names and pin groups apply to all enabled sites, unless the pin name explicitly specifies the site. You can specify a pin in a specific site  using the form siteN/pinName,  where N is the site number.

Valid values of `channel_list` parameter are:
- Channel number(s). e.g. '0', '0-7'
- Comma-delimited pins/pin groups that apply to all sites. e.g. 'VCC, CLK'
- Comma-delimited pins/pin groups that applies to specific site. e.g. 'site2/VCC, site2/CLK'

Ideally, the above cases should be coded in Python as:
```
session.channels['0-7'].ppmu_voltage_level = 4
session.pins['VCC,CLK'].ppmu_voltage_level = 4
session.sites[2].pins['VCC,CLK'].ppmu_voltage_level = 4
```

The 1st way is already available in nidigital API. The 2nd way would require adding `pins` as a repeated capability.
The 3rd way would require the session object to hold 2 active repeated capability objects, which would require changes to code generator.

**Comment by marcoskirsch** [comment]
I think `#1` and `#2` are no brainers. The real question is whether `#3` is desirable and how we would accomplish it.
