### ISSUE TITLE
command_history.bat/.sh contains system path information

### ISSUE THREAD

**Issue by marcoskirsch** [ni/nimi-python#110]
We generate command_history scripts for client convenience in order to "replay" the build. Every time I build, the files change if the last machine where they were created is different. Large part of the changes stem from the fact that full paths are used in the scripts:

For example this:

    python3 -m build --template  /mnt/d/GitHub/nimi-python/build/templates/enums.py.mako --dest-dir  /mnt/d/GitHub/nimi-python/bin/nidmm/nidmm/ --metadata  /mnt/d/GitHub/nimi-python/src/nidmm/metadata 

Becomes

    python3 -m build --template  /Users/kirsch/Developer/nimi-python/build/templates/enums.py.mako --dest-dir  /Users/kirsch/Developer/nimi-python/bin/nidmm/nidmm/ --metadata  /Users/kirsch/Developer/nimi-python/src/nidmm/metadata 

I think we should change the generation so that the script only includes relative paths from the mimi-python directory. Clients can invoke:

    ./generated/command_history.sh

**Comment by Fladolcetta** [comment]
Closed and superseded by issue #178
