### ISSUE TITLE
Remove type from method name `write_source_waveform_broadcast_u32`

### ISSUE THREAD

**Issue by marcoskirsch** [ni/nimi-python#1105]
### Description of issue

`nidigital` has a method `Session.write_source_waveform_broadcast_u32`. In Python there is no U32 type. If the C function has a "U32" suffix because we think we may add other flavors of the function that is fine. In Python we should use "fancy" functions when that happens.

**Comment by texasaggie97** [comment]
Already in work with #1096

**Comment by sbethur** [comment]
#1096 is for `fetch_capture_waveform_u32`. This issue is for `write_source_waveform_broadcast_u32`.

**Comment by texasaggie97** [comment]
Oops. Missed that.

**Comment by marcoskirsch** [comment]
> Already in work with #1096

Then it should be closed when #1096 gets merged.
