### ISSUE TITLE
command_history.sh is not executable as built

### ISSUE THREAD

**Issue by marcoskirsch** [ni/nimi-python#111]
After building:

    Kirsch0:nimi-python kirsch$ ./generated/command_history.sh
-bash: ./generated/command_history.sh: Permission denied

I suppose we could add a build step to chmod. But we're putting the files under source control so when someone without make pulls the script, it won't be executable right away (or does Git pull permissions?)

I suppose the likelihood of needing the script is pretty low for a Unix user since they tend to have GNU Make in the system.

**Comment by Fladolcetta** [comment]
Closed and superseded by issue #178
