### ISSUE TITLE
Erroneously passing lib and .so decorations to find_library on Linux

### ISSUE THREAD

**Issue by lkolbly** [ni/nimi-python#1140]
Question about library singleton.py. It looks like we recently changed it to pass the DLL name through find_library ([here](https://github.com/ni/nimi-python/commit/54ab723c78415ca90ca3986b7c2a91f588e268d3)), but the DLL names contain "lib" and ".so" -fixes ([here](https://github.com/ni/nimi-python/blob/master/generated/nidmm/_library_singleton.py#L15)), but find_library does not like those prefixes ([here](https://docs.python.org/3/library/ctypes.html#finding-shared-libraries)). This appears to be causing an issue on @Fladolcetta's machine with DMM on OpenSUSE, should we put together a PR for that?

**Comment by marcoskirsch** [comment]
>should we put together a PR for that?

That'd be great. This fix would warrant a release IMO.
