### ISSUE TITLE
Use Windows Subsystem for Linux in nimi-bot

### ISSUE THREAD

**Issue by marcoskirsch** [ni/nimi-python#1142]
nimi-bot CI builds using MinGW. Per #1141 and in order to make nimi-bot more like a developer's system, we should change it to use Windows Subsystem for Linux.

**Comment by sbethur** [comment]
I can do this since I setup the env. recently.

**Comment by texasaggie97** [comment]
This is now N/A since we no longer build anything on nimi-bot and instead rely on what has been built and committed.
