### ISSUE TITLE
Need to update "test_query_max_current_limit" system test for nidcpower

### ISSUE THREAD

**Issue by bhaswath** [ni/nimi-python#1154]
### Description of issue

    The behavior has changed, now simulated devices will create a high cooling chassis instance. The default value for max current limit on high cooling chassis should be 0.1A. Currently it is listed as 0.06A( which was what was expected on low cooling chassis)

### System report

`python -c "import niscope; niscope.print_diagnostic_information()"` output (replace `niscope` with appropriate package name)

    ```
    <Replace with the output of the above command>
    ```

### Steps to reproduce issue

    ``` python
    <Replace with a script that clearly shows the issue, if applicable>
    ```

    1. Step 1
    2. Step 2
    3. etc...

**Comment by marcoskirsch** [comment]
What version of NI-SCOPE runtime introduces this change?
