### ISSUE TITLE
tox-globinterpreter doesn't work on Python 3

### ISSUE THREAD

**Issue by marcoskirsch** [ni/nimi-python#1170]
### Description of issue

We rely on [tox](https://pypi.org/project/tox/)  during system tests in order to run the tests on all supported version of Python.
nimi-python is uncommon in the sense that we care very much about testing on both 32-bit and 64-bit interpreters (we interact with C libraries which may return data packed differently based on bitness).

Since tox doesn't provide a native way to differentiate between 32 and 64 bit Python interpreters, we use [tox-globinterpreter](https://bitbucket.org/ruamel/tox-globinterpreter/src/default/). Unfortunately, this tool doesn't work on Python 3, it hasn't been touched since 2015, and the [developer is not responsive](https://bitbucket.org/ruamel/tox-globinterpreter/issues/1/does-not-work-on-python-3x).

Python 2.7 [is EOL](https://pythonclock.org), so we want to completely stop using it in this project. That means we need to either fix tox-globinterpreter which would require a fork, or we need to find an alternative.

**Comment by texasaggie97** [comment]
We have worked around this by having multiple agents running the system tests. One will run against 32 bit Pythons, and the other will run them against 64 bit Pythons.
