### ISSUE TITLE
nitclk example(s) needed

### ISSUE THREAD

**Issue by marcoskirsch** [ni/nimi-python#1177]
### Description of issue

We only have a placeholder.
We think an example that synchronizes a signal generator with a digitizer would be good.

**Comment by gfisher-NI** [comment]
@marcoskirsch This issue has come up again recently. A customer is trying to sync four PXIe-5451's with an external trigger using nitclk.configure_for_homogeneous_trigger . The existing example nitclk_configure.py does exactly nothing:

![image](https://user-images.githubusercontent.com/68872082/101682313-0fea1000-3a29-11eb-8730-16ee616a0e9b.png)

**Comment by marcoskirsch** [comment]
@gfisher-NI Want to do a PR?

**Comment by gfisher-NI** [comment]
@marcoskirsch Sure, I'll see if I can get an example working this week.
