### ISSUE TITLE
`nidigital` driver runtime's description is incomplete.

### ISSUE THREAD

**Issue by marcoskirsch** [ni/nimi-python#1204]
### Description of issue

nimi-python refers to the driver underneath the `nidigital` module as "NI-Digital" but its real, full, correct name is "NI-Digital Pattern Driver".

I didn't come up with it, don't shoot the messenger.

See https://www.ni.com/en-us/support/downloads/drivers/download.ni-digital-pattern-driver.html#320889

**Comment by sbethur** [comment]
Verified that #1207 fixed all instances of "NI-Digital" and there are no others left.
