### ISSUE TITLE
Unable to find enum EnabledSetting

### ISSUE THREAD

**Issue by injaleea** [ni/nimi-python#121]
configure_offset_comp_ohms() , configure_adc_calibration(), configure_auto_zero_mode() methods use enum EnabledSetting. There is no enum EnabledSetting defined in enum.py

CableCompensationType , ADCCalibration, AutoZero are defined in enum. But unable to use them since function.py is throws error when not matching enumtype  EnabledSetting.

```
def configure_auto_zero_mode(self, auto_zero_mode):
        if type(auto_zero_mode) is not enums.EnabledSetting:
            raise TypeError('Parameter mode must be of type ' + str(enums.EnabledSetting))
        error_code = self.library.niDMM_ConfigureAutoZeroMode(self.vi, auto_zero_mode.value)
        errors._handle_error(self, error_code)
        return
```

**Comment by texasaggie97** [comment]
Not actually fixed
