### ISSUE TITLE
nimi-bot tests should validate "Driver Version Tested Against"

### ISSUE THREAD

**Issue by marcoskirsch** [ni/nimi-python#1314]
Our README.md file includes "Driver Version Tested Against" information. This is maintained manually and it is very error prone to maintain.

We should be able to get add a system test that grabs the version from the driver runtime and compares against the "Driver Version Tested Against" shown in the README.md, and fail if they don't match.

**Comment by AlexHearnNI** [comment]
This looks like a duplicate of Issue #1136.

**Comment by marcoskirsch** [comment]
Indeed. Closing.
