### ISSUE TITLE
Some methods in nidigital could (should?) use `sites` rep cap

### ISSUE THREAD

**Issue by marcoskirsch** [ni/nimi-python#1337]
As of #1290 we have a `sites` repeated capabilities object in `nidigital`. Two methods were not made to take advantage:

1. `fetch_history_ram_cycle_information`
2. `get_history_ram_sample_count`

I suspect this is because they only allow one site at a time. I don't think that's a good reason as we have functions in other APIs that only allow one channel. We let the driver runtime error if the user passes more than one.

```python
hram_info = my_session.pins["VCC"].fetch_history_ram_cycle_information(3)
```

should become

```python
hram_info = my_session.sites[3].pins["VCC"].fetch_history_ram_cycle_information()
```

**Comment by sbethur** [comment]
`fetch_history_ram_cycle_information` already uses `pins` repeated capability. So, it cannot use `sites` repeated capability; at least with the way we're currently nesting rep caps. Users typically use `get_history_ram_sample_count` and `fetch_history_ram_cycle_information` together. For the sake of consistency, I decided to not use `sites` rep cap for both.

**Comment by sbethur** [comment]
`is_site_enabled` is the other method without `sites` rep-cap, which I'd argue should use the rep cap.

**Comment by marcoskirsch** [comment]
One way to implement this is to create "fancy" function that parses the `self._repeated_capability` string and breaks it up into two parameters.
