### ISSUE TITLE
Unit tests run every time you make, even if nothing changed

### ISSUE THREAD

**Issue by marcoskirsch** [ni/nimi-python#136]
Introduced by https://github.com/ni/nimi-python/pull/133 which fixes https://github.com/ni/nimi-python/issues/124 (this new issue is less severe).
We need a bit more smarts in our makefiles so that we don't re-run unit tests if nothing changed _and_ last unit test run passed.

**Comment by texasaggie97** [comment]
Wheels also rebuild every time.
