### ISSUE TITLE
Publish nidigital 0.5

### ISSUE THREAD

**Issue by sbethur** [ni/nimi-python#1361]
### Description of issue

nidigital API has been finalized. Currently, we are working on tests to verify the API. While that is going on, we should publish the current API on PyPI, so users can start using it and provide feedback.

**Comment by mroeleke** [comment]
Hi @sbethur,
when will you publish version 0.5?

**Comment by sbethur** [comment]
Hi @mroeleke,
We are targeting to release 0.5 once we fix all issues in [API finalization milestone](https://github.com/ni/nimi-python/milestone/20). Currently, it's looking like it will be at least a week to complete that.

If you need a build before that, I can publish 0.4.1 now.

**Comment by mroeleke** [comment]
Hi @sbethur,
yes, can you please release a version 0.4.1 shortly?

**Comment by sbethur** [comment]
@mroeleke, nidigital 0.5 is released.
