### ISSUE TITLE
datetime.timedelta does not provide the necessary resolution for many methods and properties in nidigital

### ISSUE THREAD

**Issue by sbethur** [ni/nimi-python#1368]
### Description of issue

`datetime.timedelta` has a microsecond resolution, which is not sufficient for many method parameters, return values, and properties. e.g. edge placement, vector period, TDR offset etc.

**Comment by sbethur** [comment]
@marcoskirsch, I see `datetime.timedelta` being used in other nimi-python modules. Is there a resolution issue in any of those too?

**Comment by marcoskirsch** [comment]
No, all the places in which we use `datetime.timedelta` we verified the resolution is sufficient.

**Comment by texasaggie97** [comment]
There is already an issue for this: #744 

Though so far it hasn't been a real issue, just a theoretical issue.

**Comment by sbethur** [comment]
Implementation notes from Mark on how to add `hightime` as a dependency to `nidigital` installer:

> You would need to touch setup.py.mako, tox-system_tests.ini.mako, and tox.ini and then rebuild.

**Comment by sbethur** [comment]
#1438 updated nidigital installer to consume hightime library but the code hasn't been updated to use hightime types yet.
