### ISSUE TITLE
Do not use PXIe-5421 for test_get_self_cal_last_date_and_time in nifgen

### ISSUE THREAD

**Issue by sbethur** [ni/nimi-python#1375]
### Description of issue

Due to internal bug# 999932, PXIe-5433 cannot be used in `test_get_self_cal_last_date_and_time` in nifgen; we fall back to using persistent simulation session of PXIe-5421, which results in the test being quite slow.

When the aforementioned bug is fixed, test should be updated to use PXIe-5433, just like the rest of the nifgen tests.

**Comment by ni-jfitzger** [comment]
We were not using persistent simulation. It was IVI simulation.
