### ISSUE TITLE
Do not use PXIe-5421 for create_advanced_arb_sequence tests in nifgen

### ISSUE THREAD

**Issue by sbethur** [ni/nimi-python#1376]
### Description of issue

Due to internal bug# 227842, PXIe-5433 cannot be used in tests for `create_advanced_arb_sequence` in nifgen; we fall back to using persistent simulation session of PXIe-5421, which results in the test being quite slow.

When the aforementioned bug is fixed, test should be updated to use PXIe-5433, just like the rest of the nifgen tests.

**Comment by sbethur** [comment]
Internal bug# 227842 has been fixed and test machine has be updated with the fix. This issue is ready to be worked on.

**Comment by ni-jfitzger** [comment]
We were not using persistent simulation. It was IVI simulation.
