### ISSUE TITLE
Improve usability of loading specifications, levels, and timing files and unloading specifications in nidigital

### ISSUE THREAD

**Issue by sbethur** [ni/nimi-python#1392]
### Description of issue

Users typically load multiple levels files, multiple timing files, and at least one specifications file. Currently this requires `load_levels()`, `load_timing()`, and `load_specifications()` to be called in separate loops.

Usability can be improved by exposing a single method that allows multiple files of all three kinds to be loaded, similar to [Load Specifications Levels and Timing](https://www.ni.com/documentation/en/ni-digital/latest/ni-digital-node-ref/load-spec-levels-timing-multiple/) in LV.

Similarly API should provide a method to [unload multiple specifications files](https://www.ni.com/documentation/en/ni-digital/latest/ni-digital-node-ref/nidigital-unload-specs-single/) in a single method call.

**Comment by marcoskirsch** [comment]
This ask doesn't make the API more Pythonic, it's just an improvement that would be equally applicable to LabVIEW and C and .NET APIs.

So I don't think it's a good idea to add it as a Python-specific deviation.

**Comment by sbethur** [comment]
It won't be Python-specific. We have these as Poly VIs in LabVIEW, which are very similar to what I'm proposing in Python. In .NET, we have them in slightly different form - 3 different methods for specs, levels, and timing; each capable of loading one or more files. It had to be done like that in .NET because language doesn't support multiple optional parameters. If anything, C is the outlier; which is the case for many other parts of the API too.
