### ISSUE TITLE
niScope_GetChannelName() and niScope_GetChannelNameFromString() missing from niscope Python bindings

### ISSUE THREAD

**Issue by sbethur** [ni/nimi-python#1402]
### Description of issue

`niScope_GetChannelName()` and `niScope_GetChannelNameFromString()` are present in NI-SCOPE C API, but missing in `niscope` Python bindings.

`get_channel_names(indices)` should be added to `niscope` Python bindings to cover for the 2 C entry-points mentioned above.

See [here](https://github.com/ni/nimi-python/issues/1386#issuecomment-612224495) for details of behavior, implementation notes, and rationale behind `get_channel_names(indices)`.

**Comment by marcoskirsch** [comment]
At this point we’d only want `get_channel_names` in the Python API.

**Comment by ni-jfitzger** [comment]
It appears this will be a requirement for fixing #1770.
I implemented a fix for that issue based on what we do for nidcpower, but it doesn't work because get_channel_names isn't available to get `_all_channels_in_session`.
