### ISSUE TITLE
Create fake driver for test purposes

### ISSUE THREAD

**Issue by marcoskirsch** [ni/nimi-python#143]
We should provide fake driver metadata (NI-FAKE) that includes one instance of each API option we need to work with. The Python bindings for NI-FAKE would obviously not work on any real driver, but would be perfect for unit testing. This way we don't need to unit test each real driver, which is very repetitive and burdensome as there are many of them and they are large; nor do we need to go through the drivers and make sure we are covering every special case that the code generator needs to handle.

**Comment by Fladolcetta** [comment]
Fixed by #149
