### ISSUE TITLE
Enhancement of Nidigital Frequency Counter Measure Frequency Methode

### ISSUE THREAD

**Issue by mroeleke** [ni/nimi-python#1447]
For using this methode in nidigital I would like to be able to choose the measurement edge and the measurement window for the freq measurement.
It seams the methode is using the rising edge, which in my case is not very stable.

Use Case:  Measuring the output data rate (ODR) of a sensor (Range 100 Hz to 64kHz) on the interrupt pin
1. Configure the device to interrupt data ready in interrupt pin
2. Measuring interrupt pulse frequency, which is basically the ODR
-> interrupt pin is an open drain pad, which can only pull to low, the pull high is done via active load or pull up resistor.
-> That means the "sharp" edge is the falling edge, not the rising, because of the bus load it may take a while and it is not really a edge but more a ramp

It would also be nice to be able to specify the time f the frequency  measurement directly.

**Comment by sbethur** [comment]
@mroeleke,

Being able to choose the measurement edge is a feature that requires underlying driver and/or hardware to support. For such requests (i.e. not specific to nimi-python), please open a request through [NI support portal](https://www.ni.com/en-us/support.html). Sorry for the inconvenience, but this allows us to track, prioritize, and service feature requests faster and more efficiently.

>.. measurement window for the freq measurement.

I'm assuming this is the same as specifying the measurement time for frequency counter. You can do this by setting this property:
https://github.com/ni/nimi-python/blob/b32cba14c2a15803fd930b6420851d41fe87ad23/generated/nidigital/nidigital/session.py#L236
