### ISSUE TITLE
niscope module does not expose calibration info functionality

### ISSUE THREAD

**Issue by marcoskirsch** [ni/nimi-python#1463]
The following functions exist in NI-SCOPE runtime and can be accessed through a regular (not calibration) session. Yet they are not exposed in `nimi-python`. Equivalent methods are exposed in `nimi-python` for other driver modules. 

* niScope_CalFetchDate
* niScope_CalFetchTemperature
* niScope_CalFetchCount
* ~~niScope_CalFetchMiscInfo~~ will be handled in #1464 

When adding to nimi-python, we should make sure they are exposed in a way that is consistent with the other drivers in order to allow duck-typing usage.

NI-SCOPE uses an enum to select between self/external/manufacturing. We probably would be ok exposing self/external only as separate methods like all the other APIs do.

**Comment by marcoskirsch** [comment]
Related issue: #1462

**Comment by marcoskirsch** [comment]
Internal Bug 1038236: A customer ran into this issue and needs the cal date functionality exposed.

**Comment by shilohbeeler-NI** [comment]
> niScope_CalFetchCount
> niScope_CalFetchMiscInfo
Could you point me to an equivalent implementation of either of these two in another module? I'm unable to find any. I've got the other two handled but I don't want to try writing the metadata for these two from scratch unless necessary.

**Comment by marcoskirsch** [comment]
No other module has anything like `niScope_CalFetchCount` because none of the other driver runtimes have equivalent functionality as far as I can tell. I am not sure if we should add this to `nimi-python` – we need to research a bit more. For instance: is this something supported on current modules or only on EOL ones?

`niScope_CalFetchMiscInfo` is equivalent to:

* `niDCPower_GetCalUserDefinedInfo`
* `niDMM_GetCalUserDefinedInfo`
* `niFgen_GetCalUserDefinedInfo`

Why is NI-SCOPE inconsistent? Great question.
We should expose all four consistently in `nimi-python` in my opinion because Duck Typing.
