### ISSUE TITLE
Test code should be separate from module code

### ISSUE THREAD

**Issue by thejcannon** [ni/nimi-python#1475]
(Copied from #1473)

Having the tests be in the same file as the source code is not something I'd expect when installing a Python module.

- It pollutes the API of the module (attribute discovery will show a bunch of unrelated functions)
- It can pollute the module's dependencies
- It bloats the installed modules (more LOC to download and sift through)
- It makes features such as `pytest`'s `conftest.py` harder to use.

If you want people to be able to run tests after installation you should allow installation using an extra (like `nidmm[test]`)

**Comment by sbethur** [comment]
#1477 should fix this issue for `converters`. With that, none of the "shipping" modules should have this problem.
But there are other modules in [helper folder](https://github.com/ni/nimi-python/tree/master/build/helper), which are used during codegen, that we need to fix.

**Comment by thejcannon** [comment]
:rocket:
