### ISSUE TITLE
Factor out duplicate logic into a helper function for NI-SCOPE fancy functions

### ISSUE THREAD

**Issue by shilohbeeler-NI** [ni/nimi-python#1496]
### Description of issue

For some of the fancy functions in NI-SCOPE, there exists code in the wrappers which is either identical or very similar. This code should be factored out into a helper function in order to optimize code reuse.

See: [fancy_fetch_array_measurement.py.mako](https://github.com/ni/nimi-python/blob/02859f9d093e4251dae907f8e023d31f4887811e/src/niscope/templates/session.py/fancy_fetch_array_measurement.py.mako#L26) and [fancy_fetch.py.mako](https://github.com/ni/nimi-python/blob/02859f9d093e4251dae907f8e023d31f4887811e/src/niscope/templates/session.py/fancy_fetch.py.mako#L26), for example.

**Comment by sbethur** [comment]
@shilohbeeler-NI, can you please link the piece of code in question.
