### ISSUE TITLE
Publish nidigital 1.0.0 on PyPI

### ISSUE THREAD

**Issue by sbethur** [ni/nimi-python#1528]
### Description of issue

Publish nidigital 1.0.0 on [PyPI](https://pypi.org/project/nidigital/)

**Comment by ni-jxie** [comment]
@marcoskirsch @sbethur @phindman I believe this is the last issue we need to do for nidigital 1.0 Python release, hooray! When can we make this happen and celebrate?

**Comment by marcoskirsch** [comment]
Very exciting. Good work.

#1540 and #1541 ... Do we want them in?

**Comment by sbethur** [comment]
I have one PR left to submit for `nidigital`, which I'll do today.

If #1540 and #1541 can be submitted in 1-2 days, I can wait before doing the release. @gfisher-ni, do you have the bandwidth to complete these?

**Comment by gfisher-NI** [comment]
@sbethur I intend on working on those today, so, hopefully, yes.

**Comment by ni-jxie** [comment]
#1540 and #1541 are in! @sbethur Are we ready to do the release?

**Comment by marcoskirsch** [comment]
Yep!
Expect it soon.

**Comment by sbethur** [comment]
nidigital 1.0.0 has been released!!

https://github.com/ni/nimi-python/releases/tag/1.3.3
