### ISSUE TITLE
Powerline Frequency should be enum instead of float

### ISSUE THREAD

**Issue by injaleea** [ni/nimi-python#153]
```
def configure_power_line_frequency(self, power_line_frequency_hz):
     error_code = self.library.niDMM_ConfigurePowerLineFrequency(self.vi, power_line_frequency_hz)
     errors._handle_error(self, error_code)
      return
```
Ideally powerline frequency should be enum which has 50Hz and 60Hz like LabVIEW APIs does. There is an enum(PowerlineFrequency) defined in enum.py but not used in session.py.

**Comment by marcoskirsch** [comment]
The Python API is modeled after our C API, not our LabVIEW API.
C function [niDMM_ConfigurePowerLineFrequency](http://zone.ni.com/reference/en-XX/help/370384N-01/dmmcref/cvinidmm_configurepowerlinefrequency/)  uses a ViReal64.
This matches the [NIDMM_ATTR_POWERLINE_FREQ attribute](http://zone.ni.com/reference/en-XX/help/370384N-01/dmmcref/canidmm_attr_powerline_freq/).

Will close.
