### ISSUE TITLE
Add nidcpower system tests for "with channels" functions

### ISSUE THREAD

**Issue by marcoskirsch** [ni/nimi-python#1591]
In #1589 the underlying function called by methods in `nidcpower` was switched over to use the new "with channels" flavors in NI-DCPower runtime.

But the system tests do not exercise anything other than "all channels" because `__init__` doesn't use `niDCPower_InitializeWithIndependentChannels` yet.

Once that's fixed, the system tests need to be fleshed out for coverage.

**Comment by smooresni** [comment]
This issue is related to #1614
