### ISSUE TITLE
command_history.bat doesn't work

### ISSUE THREAD

**Issue by marcoskirsch** [ni/nimi-python#161]
We generate [command_history.bat](https://github.com/ni/nimi-python/blob/master/generated/command_history.bat) at build time, presumably so a developer can replay the commands run by make or so that a developer  can inspect the commands run by make.

The batch file won't work, however, even on the same system, because the paths aren't suitable for Windows: it has forward slashes, and it uses / as the file system root.

**Comment by Fladolcetta** [comment]
Closed and superseded by issue #178
