### ISSUE TITLE
nidigital：write_source_waveform_broadcast(waveform_name, waveform_data)  waveform_data type is？

### ISSUE THREAD

**Issue by Super-leilei** [ni/nimi-python#1613]
session.pins['RFFEDATA'].create_source_waveform_serial('RegWrite',data_mapping,1,bit)
session.write_source_waveform_broadcast('RegWrite',[1,0,0,0,1,1,1,0,0,1,0,0,1,0,0,1,1,0,1])

Whether the above method is correct, trouble to inform, thank you!

**Comment by sbethur** [comment]
Please do not create issues for asking questions, use [discussions](https://github.com/ni/nimi-python/discussions) for that.

I've started a new discussion for your question: https://github.com/ni/nimi-python/discussions/1616
