### ISSUE TITLE
Please check the Python code I wrote to control NI_Digital to read and write the "MIPI" register

### ISSUE THREAD

**Issue by Super-leilei** [ni/nimi-python#1617]
I am using "Pxie 6570" to read and write" MIPI "register. I am using the" nidigital "library in Python, but my register read back is always 0. Please help me check the code, thank you very much!
Attached are the Python code and the project file of the “Digital Pattern”
[python_code.zip](https://github.com/ni/nimi-python/files/6568759/python_code.zip)
 @marcoskirsch @lkolbly @juno-jin-ni

**Comment by smooresni** [comment]
@Super-leilei you might find [this](https://github.com/NISystemsEngineering/mipi-rffe-python/tree/oop-dev) reference architecture to be a good starting point.

**Comment by sbethur** [comment]
@Super-leilei, please use GitHub issues only for ideas, enhancements, tasks, or bugs in nimi-python.
