### ISSUE TITLE
Python script reference for controlling NI-PXIe5840

### ISSUE THREAD

**Issue by Super-leilei** [ni/nimi-python#1630]
Hello, do you have a Python script reference for controlling NI-PXIe5840, or NI-RFSA, thank you!

**Comment by sbethur** [comment]
nimi-python repo is for drivers listed [here](https://github.com/ni/nimi-python#about). For queries related to other devices and drivers, please visit [NI Community Forums](https://forums.ni.com/?profile.language=en).
