### ISSUE TITLE
Topology constants haven't been updated on help page

### ISSUE THREAD

**Issue by jazbell3** [ni/nimi-python#1652]
### Description of issue

The topology constants on [this page](https://nimi-python.readthedocs.io/en/master/niswitch/class.html#methods) have changed and need to be updated. I referenced the LabVIEW examples for niswitch to find the proper constants.

**Comment by sbethur** [comment]
The topology constants listed cannot be used in Python and hence we should delete them from Python documentation.

**Comment by marcoskirsch** [comment]
@tobiasgordon needs to update `niswitch` metadata. The fix is already contained there but hasn't been updated in this repository.
