### ISSUE TITLE
The examples path in documentation is ambiguous

### ISSUE THREAD

**Issue by sbethur** [ni/nimi-python#1682]
### Description of issue

In the [Usage](https://nimi-python.readthedocs.io/en/master/nidcpower.html#usage) section, the text says:

> Additional examples for NI-DCPower are located in src/nidcpower/examples/ directory.

The path is ambiguous - it can mean the src folder in the GitHub repo or src folder on a Linux machine with nimi-python module installed. It should unambiguously mean the src folder in the GitHub repo.

**Comment by marcoskirsch** [comment]
Duplicate of #1612.
