### ISSUE TITLE
 Returned parameter which is marked as unused in Python API  still gets codegen-ed into the documentation 

### ISSUE THREAD

**Issue by sbethur** [ni/nimi-python#1698]
There is an existing bug with the codegen logic where return parameter which is marked as unused in Python API (i.e. by specifying 'use_in_python_api': False in python/functions/functions.hapigen) still gets codegen-ed into the documentation
![image](https://user-images.githubusercontent.com/48041236/158897394-e98c0e2f-213b-4c93-a339-b259368a0ed7.png)
although it no longer gets returned by the actual code:

return [ni_lcr_measurement.NILCRMeasurement(measurements_ctype[i]) for i in range(count_ctype.value)]

Include relevant system information, steps to reproduce, and any workarounds.

**Comment by ni-jfitzger** [comment]
My guess: change this line: https://github.com/ni/nimi-python/blob/f3324c733daaa52f7d7d2cc6a131d2268f77404d/build/helper/metadata_filters.py#L251

to
`        if x['direction'] == 'out' and (options_to_use['skip_output_parameters'] or not x['use_in_python_api']):`

**Comment by ni-jfitzger** [comment]
Fixed by #1822

**Comment by ni-jfitzger** [comment]
Fixed by #1822
