### ISSUE TITLE
Temporary disabling of the new NI-DCPower metadata to ease code review

### ISSUE THREAD

**Issue by olsl21** [ni/nimi-python#1715]
### Description of issue

The new NI-DCPower 21.8.0f382 metadata include many new attributes, enums, custom_types and functions. They should be disabled temporarily through addon metadata before being re-enabled through subsequent smaller PRs.

**Comment by marcoskirsch** [comment]
@olsl21 you can close this, correct?

**Comment by olsl21** [comment]
@marcoskirsch Yes, all the temporarily disabled new NI-DCPower metadata have been re-enabled as of https://github.com/ni/nimi-python/commit/f95e90f20d92f27ca3ea8d900125741327607d12, I'll close this issue.
