### ISSUE TITLE
NI-DCPower: Calling `session.channels["2"].get_channel_name()` or `get_channel_names()` should raise a more relevant / specific exception

### ISSUE THREAD

**Issue by olsl21** [ni/nimi-python#1759]
### Description of issue

Currently, calling `session.channels["2"].get_channel_name()` or `session.channels["2"].get_channel_names()` would result in `AttributeError: '_SessionBase' object has no attribute 'get_channel_name'`. Ideally, we could improve on it and raise a custom exception that is more relevant and specific. This fix may be applicable to other drivers as well.

**Comment by marcoskirsch** [comment]
To fix this we'd probably need to codegen stubs for all properties and methods in _SessionBase that do nothing but raise `AttributeError` with a nicer string.

So while the error we raise now isn't very helpful to customers, improving it would add more complexity than we deem worth it to the generated code.
