### ISSUE TITLE
Codegen only the attribute classes that are used

### ISSUE THREAD

**Issue by olsl21** [ni/nimi-python#1762]
### Description of issue

Currently, the generator generates all the Attribute classes in `_attributes.py.mako` for all drivers even if some of them are not used.
We should make the generator smarter so that only the Attribute classes that are used get generated.

Kindly refer to https://github.com/ni/nimi-python/pull/1738#discussion_r904141387 for more details.

**Comment by marcoskirsch** [comment]
The dead code is harmless and we won't realistically get to this.
