### ISSUE TITLE
NI-DCPower: Store all the channel names in the session to avoid having to call `_get_channel_names()` repeatedly during fetch/measure multiple

### ISSUE THREAD

**Issue by olsl21** [ni/nimi-python#1776]
### Description of issue

The current implementation of #1754 calls `_get_channel_names()` as part of `fetch_multiple()` and `measure_multiple()`, which is inefficient as the channel names in a session won't change. A suggestion is to store the result of calling `get_channel_names()` as a member variable of `Session` (i.e. `_all_channels_in_session`) and pass it to `_SessionBase` as part of its constructor so that it can be reused.

Related discussions:
https://github.com/ni/nimi-python/pull/1754#discussion_r912288175
https://github.com/ni/nimi-python/pull/1754#discussion_r917113448
https://github.com/ni/nimi-python/pull/1754#discussion_r918402450

**Comment by marcoskirsch** [comment]
An alternative to doing in `Session.__init__` would be to do it only when first needed.
