### ISSUE TITLE
Upgrade nimibot drivers to 2022 Q3 releases

### ISSUE THREAD

**Issue by marcoskirsch** [ni/nimi-python#1788]
Before releasing support for 2022 Q3 released APIs we need to make sure we are running our system tests against those driver runtimes. For that, we need to upgrade nimibot. The following drivers have newer releases:

NI-DCPower
NI-DMM
NI-SCOPE which includes NI-TClk
NI-Digital Pattern Driver

**Comment by sbethur** [comment]
Internal pipeline was used to update the VM image with latest driver runtimes.
