### ISSUE TITLE
nifgen Python API streaming support ? 

### ISSUE THREAD

**Issue by okz** [ni/nimi-python#1807]
The Python nifgen API seems to have streaming support, but haven't seen any examples or tests using streaming. Are there any known limitations ? 

Planning to test following "\niFgen\documentation\English\SigGenHelp.chm::/streaming.html"  but wondered if the indicated transfer rates can be achieved with the Python API.  I am hoping ~50MB/s transfer rates would be possible. 

![image](https://user-images.githubusercontent.com/3274852/184100898-b8be0b4b-6edf-476a-81f5-b0e31b2fbbe3.png)

Kind regards,
Oz

**Comment by marcoskirsch** [comment]
You will be limited by system performance. I'm curious to see if you can accomplish the desired rate on your setup. Please report back!

(I expect you will be able to hit it, but I don't know what PC you have nor what instrument model you are using).

**Comment by okz** [comment]
Just to update that, using numpy arrays and using the python API 's lower level private _write functions, ~40MB/s was achieved. 

Best results were through various remote controllers, MXI-3 etc, using modern CPU's. The NI embedded controllers I had access to were 15years old, and didn't get much above 20MB/s

**Comment by marcoskirsch** [comment]
Good to hear. I am a bit baffled that you had to use "lower level private _write functions". Those are a bad idea for your code to call into directly as we make no source compatibility guarantees for them. Did using the public methods impact your code's performance severly?

**Comment by marcoskirsch** [comment]
Consider pasting a small example of how you accomplished it.
