### ISSUE TITLE
Channels Context Manager for properties and functions (“with session.channels(‘0’) as c:”)

### ISSUE THREAD

**Issue by Fladolcetta** [ni/nimi-python#185]
On multi-channel sessions (think NI-DCPower), often times customer wants to call functions or set/get attributes on specific channel(s).

We want to create a context manager that allows doing exactly this without having to pass the same channel parameter in multiple calls. In LabVIEW, you get equivalent functionality for properties by using the Active Channel input in the property node.

    my_session.do_foo("0,1", 5)
    b = my_session.get_foo("0,1")
    # One way, proposed in https://github.com/ni/nimi-python/issues/187
    my_session.a_property["0,1"] = 5
    # Another potential way
    my_session.set("a_property", "0,1", 5)
    # getting is left as an exercise to the reader.

Could instead be achieved as:

    with my_session.channel("0,1") as channel_context:
        channel_context.a_property = 5
        value = channel_context.another_property

**Comment by epage** [comment]
Could you elaborate on what purpose this context manager would serve?

**Comment by marcoskirsch** [comment]
Added description to @Fladolcetta minimalistic description.
