### ISSUE TITLE
NI-DMM: IsOverRange and IsUnderRange are not supported

### ISSUE THREAD

**Issue by bkeryan** [ni/nimi-python#1869]
### Description of issue

The `nidmm` module does not seem to support the `niDMM_IsOverRange` and `niDMM_IsUnderRange` functions. 

### System report

```
OS:
    Name:      Windows
    Version:   10.0.22000
    Bits:      64
Driver:
    Name:      NI-DMM
    Version:   22.8.0.109
Module:
    Name:      nidmm
    Version:   1.4.3.dev0
Python:
    Version:   3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]
    Bits:      64
    Is_Venv:   False
    Installed Packages:
        pywin32==303
        setuptools==65.5.1
        pip==22.3.1
        click==8.1.3
        protobuf==3.20.3
        grpcio==1.41.1
        six==1.16.0
        wheel==0.38.4
        ni-measurement-service==0.10.2
        colorama==0.4.6
        hightime==0.2.1
        nidmm==1.4.3.dev0
```

### Steps to reproduce issue

Try to port this LabVIEW shipping example to Python:
![image](https://user-images.githubusercontent.com/17914399/202753514-003730fb-e2af-493b-bb2b-2f8bcb64991e.png)

**Comment by marcoskirsch** [comment]
This was an intentional omission.
These functions just compare the passed-in measurement value to Inf/-Inf/NaN. We don't think there's enough value in Python since a Python customer can trivially do the comparison.

**Comment by bkeryan** [comment]
@marcoskirsch Which value should clients check for?
- `IsOverRange()`: `math.isnan(x) or (math.isinf(x) and x > 0.0))`
- `IsUnderRange()`: `math.isinf(x) and x < 0.0`

**Comment by marcoskirsch** [comment]
Maybe it's not as trivial :(
