### ISSUE TITLE
marker, or start pulse width

### ISSUE THREAD

**Issue by okz** [ni/nimi-python#1873]
Hi all, 

Access to NIFGEN_ATTR_MARKER_EVENT_PULSE_WIDTH has been removed with issue #859 and pull #868.  

This is disappointing, since at high sampling speeds, the pulse can be as short as  ~150ns and can be missed by other 'sampling' HW. 

Any chance of getting it back ?  I am not aware of any other output, which is slower or can be configured slower than the sampling speed. 

Kind regards,

**Comment by marcoskirsch** [comment]
Hello @okz 
Can you list the NI-FGEN attributes that you need?
There are ways you can workaround in the interim until we add them back, if you haven't.

a) You can create and add attribute members to your `Session` object.
b) You can call `_set_attribute_vi_boolean`, etc. private methods to set the properties directly.

**Comment by okz** [comment]
Thank  you, Ended up patching the attributes 

Would suggest the group below, should be in.  NI has documented this usecase specifically:

The Marker event pulse width, tm2, is at least 150 ns and can be significantly longer than 150 ns for slower Sample clocks. You can configure the pulse width by setting the [Marker Event Pulse Width](nifgenpropref.chm::/pniFgen_MarkerEventPulseWidthValue.html) property or the [NIFGEN_ATTR_MARKER_EVENT_PULSE_WIDTH](fgencref.chm::/NIFGEN_ATTR_MARKER_EVENT_PULSE_WIDTH.html) attribute. Instruments commonly have a minimum pulse width specification for a trigger to be registered, and trigger pulses of smaller width are ignored. The signal generator ensures that a minimum pulse width exists on the Marker event by using a pulse stretching circuit. A Sample clock rate of 100 MS/s has a period of 10 ns, requiring the pulse to be lengthened for many devices to register the marker as a good trigger pulse. Refer to the [device specifications](https://github.com/ni/nimi-python/issues/nifgen_Related_Documentation.html) for the timing specifications.

        * `started_event_pulse_width`
        * `done_event_pulse_width` 
        * `marker_event_pulse_width`
        * `started_event_pulse_width_units`
        * `done_event_pulse_width_units` 
        * `marker_event_pulse_width_units`
