### ISSUE TITLE
Broken link on the nidcpower documentation page

### ISSUE THREAD

**Issue by dimapu** [ni/nimi-python#1982]
### Description of issue

This page (https://nidcpower.readthedocs.io/en/latest/class.html#reset) has a broken link, "[Programming States](https://nidcpower.readthedocs.io/en/latest/REPLACE_DRIVER_SPECIFIC_URL_1(programmingstates))" on the screenshot below.

![image](https://github.com/ni/nimi-python/assets/16896578/595c3831-295a-4dab-99e5-26cb3aeda2b6)

### System report

NA

### Steps to reproduce issue

    1. Go to https://nidcpower.readthedocs.io/en/latest/class.html#reset
    2. Click on the link "Programming states"

**Comment by ni-jfitzger** [comment]
Woohoo! People are looking at the new doc projects.

The broken link is "https://nidcpower.readthedocs.io/en/latest/REPLACE_DRIVER_SPECIFIC_URL_1(programmingstates)".
This seems very familiar. It may be a known issue.

**Comment by ni-jfitzger** [comment]
Duplicate of #1487

**Comment by dimapu** [comment]
I will close this then.

**Comment by dimapu** [comment]
Thanks for your efforts!
