### ISSUE TITLE
Add additional system tests to NI-DMM

### ISSUE THREAD

**Issue by Fladolcetta** [ni/nimi-python#202]
There are various system tests that are missing. This document will be updated with the list of remaining identified system tests.

Includes:

- test_ViInt32_output_function - 
- test_Japanese_name - 
- test_exceptions - Test a few error cases: ensure python gives you an exception with proper error code & error message from the driver, and a python stack trace.
test_initialize_with_option_string
- test_initialize_nondefault
- test_initiate_abort

**Comment by marcoskirsch** [comment]
I want to make sure everyone's on the same page as far as what system tests do.

I think in the best case System Tests only validate the correctness of the driver metadata and ensure we can load the driver and call into it correctly.

Functional validation of generated code (except low level ctypes_library.py which gets mocked) we should try and cover with NI-FAKE unit tests.

**Comment by injaleea** [comment]
Along with existing system tests PR #398 and PR #419  ensure all public methods for nidmm is called.
