### ISSUE TITLE
Getting a error when calling GetError causes a recursion failure

### ISSUE THREAD

**Issue by Fladolcetta** [ni/nimi-python#205]
If you are calling GetError and this returns an error. This throws a recusion failure.

**Comment by marcoskirsch** [comment]
If I fix https://github.com/ni/nimi-python/issues/166 I would be introducing this problem to NI-ModInst.
Should I tackle it or should I hold off? @texasaggie97

**Comment by texasaggie97** [comment]
I think it is fine to go ahead and fix #166. The reason I am okay with that is the only time we have hit this recursion failure so far is when we try to write a unit test to test that condition. I.e. it isn't very common.
