### ISSUE TITLE
Cannot initialize a device with Japanese name

### ISSUE THREAD

**Issue by bhaswath** [ni/nimi-python#208]
![jap](https://user-images.githubusercontent.com/28730126/29916713-3401f8de-8e5d-11e7-9ac3-24315fe7fac2.PNG)

For initializing with Japanese name in python, I have to encode in UTF-8, but when I try the same, I getthe error that is attached in the screenshot. By default the resource name must be encoded in ascii?

**Comment by Fladolcetta** [comment]
Closing as this is the same issue as #210
