### ISSUE TITLE
Create system for running all driver system tests automatically.

### ISSUE THREAD

**Issue by marcoskirsch** [ni/nimi-python#247]
Create a system on a dedicated computer (can be VM) that for every commit to nimi-python:

* Pulls latest code
* Builds it
* Installs it
* Runs System Tests for every driver

This system would most likely be Windows 10 with Linux Subsystem for Windows. It will need to be setup with GNU Make, Python, all drivers supported by nimi-python, etc.

Ideally it uses GitHub API and the scripts are available in nimi-python.

**Comment by Fladolcetta** [comment]
Need to document this.

**Comment by texasaggie97** [comment]
[Updated](https://github.com/ni/nimi-python/wiki/System-test-machine-configuration)
