### ISSUE TITLE
Make naming of Error and Warning classes consistent with other NI drivers.

### ISSUE THREAD

**Issue by marcoskirsch** [ni/nimi-python#253]
Follow what other NI Python driver bindings (daqmx and nixnet) as far as the naming of their Error and Warning clases.

See:

* https://github.com/ni/nidaqmx-python/blob/master/nidaqmx/errors.py
* https://github.com/ni/nixnet-python/blob/master/nixnet/errors.py

for reference

**Comment by Fladolcetta** [comment]
This is fixed. We need to add the specific pull request.

**Comment by texasaggie97** [comment]
Fixed in #231
