### ISSUE TITLE
Use warnings for errors that cannot raise for

### ISSUE THREAD

**Issue by marcoskirsch** [ni/nimi-python#254]
There's a handful of error cases throughout our code in which we cannot raise, but we ideally should give the client a way to know that they occurred. Specifically:

* If we cannot retrieve an error description - we are already in the midst of handling the error.
* If Close() returns an error - for example, because session handle became invalid.

**Comment by Fladolcetta** [comment]
Should this be an error for the Close() function??

**Comment by Fladolcetta** [comment]
Are we sure that we haven't solved the first item with the is_error_handling = True for error handling functions?
With #462 and PR #470 this should solve the second one.

Can we close this issue?

**Comment by marcoskirsch** [comment]
Agreed!
