### ISSUE TITLE
Only define types in ctypes_types.py and python_types.py that are used by the driver

### ISSUE THREAD

**Issue by Fladolcetta** [ni/nimi-python#260]
NI-ModInst generates ctypes for various types that are not used. This makes coverage look worse than it is. We should not generated unused ctypes

**Comment by marcoskirsch** [comment]
This file along with others are Mako templates but don't really need to be. I'm not convinced that adding complexity to remove unused types is worth it just to make that number appear to be better.

A better solution I think would be to leave this file out of code coverage metrics when unit testing NI-ModInst, as long as we leave it in for the NI-FAKE unit tests.
