### ISSUE TITLE
Context manager is "Acquisition" or "Generation" for all APIs

### ISSUE THREAD

**Issue by marcoskirsch** [ni/nimi-python#267]
In each driver's metadata/config.py we specify "direction" (input or output).
The code generator keys off of that in order to decide what to call the Context Manager that we return on initiate().

```
def test_acquisition(session):
    session.configure_measurement_digits(nidmm.Function.DC_CURRENT, 1, 5.5)
    with session.initiate():
        session.fetch(1000)
```

It's not a big deal because the user rarely sees the class name. But for bidirectional APIs like NI-HSDIO (which won't be added anytime soon) and for NI-SWITCH, these names are meaningless. I propose the name of the context manager itself is specified in metadata rather than we try to deduce it based on direction.

Also to consider: If the classes are to be considered private, then perhaps they should be prefixed with _.

**Comment by Fladolcetta** [comment]
The class name should be prefixed with an "_" because a client should never type this.
