### ISSUE TITLE
niswitch system test test_enum_attribute causes access violation

### ISSUE THREAD

**Issue by texasaggie97** [ni/nimi-python#268]
niswitch system test test_enum_attribute causes access violation on the system test runner

This test is commented out for now.

This appears to only affect the test machine.

**Comment by marcoskirsch** [comment]
On my test machine (Windows 7 64-bit) I ran the following code:

```
import niswitch

with niswitch.Session('', False, True, 'Simulate=1, DriverSetup=topology:2532/1-Wire 4x128 Matrix') as session:
    assert session.scan_mode == niswitch.ScanMode.BREAK_BEFORE_MAKE
```

When executed in Python 3.6.2 it works.
When executed in Python 2.7.13 it hangs.

@Fladolcetta to confirm that the same is the case on nimi-bot VM.

**Comment by marcoskirsch** [comment]
I can confirm that if I kill the Python process while it's opening a simulated session to the DAQmx switch, the system is now in a bad state. Restarting mxssvr puts me back in a good state.

I'm using a small example that runs things in a loop and prints the time:

```
import niswitch
import time

i = 0
while True:
    start = time.time()

    with niswitch.Session('', False, True, 'Simulate=1, DriverSetup=topology:2532/1-Wire 4x128 Matrix') as session:
        assert session.scan_mode == niswitch.ScanMode.BREAK_BEFORE_MAKE
    i = i + 1
    end = time.time()
    print("Iteration {0}: {1:06.3f} seconds".format(i, (end-start), " seconds"))
```

**Comment by marcoskirsch** [comment]
We've determined that this is an NI-SWITCH bug with DAQmx-based devices.
We have worked around it in the test, and filed NI internal bug 666018.
