### ISSUE TITLE
Remove hardcoded information from extracted metadata

### ISSUE THREAD

**Issue by marcoskirsch** [ni/nimi-python#273]
For historical reasons (in part related to #271) our metadata in function.py, maybe elsewhere, contains hard-coded information.
Examples:

    'codegen_method': 'public'

We should remove that and let the codegenerator add default values when it processes the metadata files.

**Comment by marcoskirsch** [comment]
Also:

     'enum':None

on every parameter for every function.

**Comment by MrDuff8** [comment]
Since these files are generated using NI internal tools, we'll track it with our internal work tracking system.
