### ISSUE TITLE
Stop copying system tests to bin/

### ISSUE THREAD

**Issue by marcoskirsch** [ni/nimi-python#286]
We copy system tests at build time, from:

    src/niswitch/system_tests/test_system_niswitch.py

to:

    bin/niswitch/system_tests/test_system_niswitch.py

If memory serves me right, we do this for historical reasons: we used to play import path tricks rather than install the modules so we needed the tests to be in a specific location relative to the built modules. This is no longer true - now we install the modules in the virtual environment. So we should be able to stop copying the files and run them from their location in src/.

**Comment by texasaggie97** [comment]
We also copy them there so the flake8 tests run on them.

Should we try to change the flake8 tests to test them in src as well?

**Comment by marcoskirsch** [comment]
> Should we try to change the flake8 tests to test them in src as well?

Yeah, unless it poses a technical challenge.
