### ISSUE TITLE
Modifying functions_addon.py doesn't properly trigger a re-build of affected files

### ISSUE THREAD

**Issue by marcoskirsch** [ni/nimi-python#292]
I modified src/nimodinst/metadata/functions_addon.py and then did a make.
Only file that got changed was generated/nimodinst/tests/mock_helper.py
I expected generated/nimodinst/session.py to change as well.

We're missing a dependency in the makefile.

Workaround: "make clean" then "make".

**Comment by Fladolcetta** [comment]
Can not reproduce here

**Comment by marcoskirsch** [comment]
Just reproduced at my desk. session.py specifically doesn't get rebuilt.
