### ISSUE TITLE
NI-FAKE Unit tests return warning

### ISSUE THREAD

**Issue by Fladolcetta** [ni/nimi-python#312]
In test_get_error_description_get_error_message
We set:

self.side_effects_helper['GetError']['return'] = -2

and this causes a warning to raise, but the test to pass.

We should add a new test to test this warning. The existing test should not have an error returned from get error.

**Comment by marcoskirsch** [comment]
Can you be more specific, which test is this? Should the test fail? What's the correct / expected behavior of the code?
