### ISSUE TITLE
Several enums in NI-DMM appear to be named incorrectly

### ISSUE THREAD

**Issue by Fladolcetta** [ni/nimi-python#324]
Some enums in NI-DMM appear incorrect with an additional underscore that is not needed:

_AC_VOLTS_DC_COUPLED
_WAVEFORM_CURRENT
_IVIDMM_MODE
_EXTERNAL
_TTL_0
_TTL_3
_TTL_7
_PXI_STAR

**Comment by marcoskirsch** [comment]
From an efficiency point of view, it makes sense to fix https://github.com/ni/nimi-python/issues/242 first.
