### ISSUE TITLE
Rename and organize build module

### ISSUE THREAD

**Issue by marcoskirsch** [ni/nimi-python#332]
Right now it looks like instead of starting out with a master plan, we started out coding and just let things evolve. Which is how it went. Which is perfectly ok. But we should now take a step back and make sure everything looks like a cohesive piece of software.

* Give the code generator module a name. nimi-pygen? nimi-python-gen?
* Get rid of cop-out generic names like helper
* Organize directories: Do we want templates inside build/ ? Do we want makefiles inside build/? Maybe?
* Rename extract_ functions to filter_*

**Comment by Fladolcetta** [comment]
Filter is complete.
