### ISSUE TITLE
close() in class Session in session.py prints a string, instead of returning it like other functions do

### ISSUE THREAD

**Issue by bhaswath** [ni/nimi-python#348]

**Comment by marcoskirsch** [comment]
Please elaborate. Why should close() return a string?

**Comment by Fladolcetta** [comment]
I believe the issue is that this is the only place where we call "print". In all other cases we raise an exception to inform the customers that something bad happened. I think the title of the issue needs to be updated.

**Comment by Fladolcetta** [comment]
As Marcos mentioned, this is already captured if you disagree, reopen.
