### ISSUE TITLE
Support iterability in addition to indexability

### ISSUE THREAD

**Issue by thejcannon** [ni/nimi-python#349]
https://github.com/ni/nimi-python/blob/c30c80a4918f78203590653590da3c91b289748b/build/templates/session.py.mako#L173-L175

For both mapping and sequence types (those which support \_\_getitem\_\_) usually iterability is supported:
```
for channel in session:
   channel.property= 4
```

**Comment by MrDuff8** [comment]
The API supports a way to set a property for multiple channels at once, allowing the driver to parallelize as much as possible. We wouldn't want to encourage this usage of the API, and we don't want to provide two ways to do the same thing.
