### ISSUE TITLE
config.py references python names for context manager. We should use C names

### ISSUE THREAD

**Issue by Fladolcetta** [ni/nimi-python#350]
'context_manager_name': {
        'task': 'scan',
        'initiate': 'initiate_scan',

Marcos wrote:

> This refers to a function using its python name.
In all other places we use the C names, for example init_function (see line 24) or when specifying parameters for buffer retrieval mechanisms.
We should be consistent about this and it seems like C names as found in metadata is the way to go.

**Comment by Fladolcetta** [comment]
@marcoskirsch 
The value here "initiate_scan", which is what is used in session.py. If we use C names here, than in the session.py.mako we would need to translate the C Name "InitiateScan" to "initiate_scan".

This seems like it would lead to potential issues. Thoughts?

**Comment by marcoskirsch** [comment]
> This seems like it would lead to potential issues. Thoughts?

It's how we do it in several other places. We should be consistent.
