### ISSUE TITLE
Pytest only passes if device is named "PXI1Slot2"

### ISSUE THREAD

**Issue by Fladolcetta** [ni/nimi-python#37]

**Comment by marcoskirsch** [comment]
As of https://github.com/ni/nimi-python/pull/69 it's Dev1.

**Comment by marcoskirsch** [comment]
Related: https://github.com/ni/nimi-python/issues/70

**Comment by marcoskirsch** [comment]
https://github.com/ni/nimi-python/pull/74#pullrequestreview-49672433
