### ISSUE TITLE
Need to create way to remove size on an input array from parameter list.

### ISSUE THREAD

**Issue by Fladolcetta** [ni/nimi-python#440]
Right now we have a function such as the following:

`session.array_input_function(test_array_size, test_array)`

We really only want to do the following:

`session.array_input_function(test_array)`

Where in functions_addon.py we specify that test_array_size is len(test_array).

**Comment by marcoskirsch** [comment]
I think this will require more metadata, something like a new size mechanism:

`['size'] = {'mechanism':'len', 'value':'testArraySize'} `

**Comment by marcoskirsch** [comment]
Note: we saw the need for this in niDCPower_SetSequence()

**Comment by Fladolcetta** [comment]
Also needed for:

- nifake array_input_function (number_of_elements)

- nidcpower create_advanced_sequence (attribute_id_count)
