### ISSUE TITLE
Errors when you have a typo in a property is misleading.

### ISSUE THREAD

**Issue by injaleea** [ni/nimi-python#466]
Running code snippet
```
with nidcpower.Session('4143', '', False, 'Simulate=1, DriverSetup=Model:4143; BoardType:PXIe') as session:
    channel = session['0']
    default_output_function = channel.output_function
    channel.function = nidcpower.OutputFunction.DC_CURRENT
```
retruning Type Error 

> E           TypeError: <nidcpower.session._RepeatedCapability object at 0x0320D3 70> is a frozen class

When setting output function for the second time to DC_CURRENT

**Comment by marcoskirsch** [comment]
If the name of the property in incorrect, then it appears like you’re adding a new property to the object. We disallow it, that’s the error you’re getting.

So it is intended behavior. Do you have any suggestions on how to improve the error? Then we can reword this issue and tag it as enhancement/API.

**Comment by injaleea** [comment]
Shouldn't be saying object has no attributes when calling an invalid function instead of telling the user about frozen class ?
