### ISSUE TITLE
niFake is missing read only and write only attributes

### ISSUE THREAD

**Issue by Fladolcetta** [ni/nimi-python#490]
Current implementation of \_\_setattr__ returns incorrect error related to attribute not existing.
I am unsure how \_\_getattr__ will function with write only attributes.

**Comment by marcoskirsch** [comment]
Can you add more details to the issue?

**Comment by Fladolcetta** [comment]
We are expecting the driver to return errors if the attribute is read-only and write-only. The reason we don't want to handle this in python is that the bindings might be mis-matched with the driver, or devices within a driver might have different rules regarding read and write leading to inconsistent errors.
