### ISSUE TITLE
Incorrect generation of nidcpower.Session. create_advanced_sequence() and SetSequence()

### ISSUE THREAD

**Issue by marcoskirsch** [ni/nimi-python#496]
This is the NI-DCPower function:

```
ViStatus _VI_FUNC niDCPower_CreateAdvancedSequence(
      ViSession vi,
      ViConstString sequenceName,
      ViInt32 attributeIDCount,
      const ViInt32 attributeIDs[],
      ViBoolean setAsActiveSequence);
```

This is the signature of the corresponding Session method:

```
    def create_advanced_sequence(self, sequence_name, attribute_id_count, attribute_ids, set_as_active_sequence=True):
```

**attribute_id_count** should not be in the method, instead it should be derived from len(attribute_ids) and passed to the library that way. We actually request that in nimi-python/src/nidcpower/metadata/functions_addon.py yet it doesn't appear to be working.

**Comment by Fladolcetta** [comment]
The issue appears that we incorrectly used passed-in instead of len in functions_addon.py.
