### ISSUE TITLE
nidcpower.Session.create_advanced_sequence parameter attribute_ids should be list of enum

### ISSUE THREAD

**Issue by marcoskirsch** [ni/nimi-python#507]
Right not it's a list of attribute IDs (int). But Python clients know nothing of those numbers. We need to provide them with an enum or some other way to refer to attributes.

**Comment by Fladolcetta** [comment]
We will need to take out Advanced Sequences altogether or fix this.

**Comment by Fladolcetta** [comment]
Closed as duplicated of #504
