### ISSUE TITLE
Write system tests for NI-SCOPE

### ISSUE THREAD

**Issue by Fladolcetta** [ni/nimi-python#520]

**Comment by injaleea** [comment]
#631, #640 will make scope system tests to cover 97%. Tests for missed methods will be written once issue #629 fixed.

**Comment by marcoskirsch** [comment]
This shouldn't have been closed yet since PR says it's a partial fix.

**Comment by Fladolcetta** [comment]
After speaking with Jaleel on this issue we are at 96% with the only missing functions being the ones for the commented out tests and there is an open issue on adding them back #650
