### ISSUE TITLE
CheckAttribute* functions not supported

### ISSUE THREAD

**Issue by marcoskirsch** [ni/nimi-python#529]
Some drivers have functions such as:

`ViStatus niFgen_CheckAttributeViInt64  (ViSession vi, ViConstString channelName, ViAttr attributeId, ViInt64 value);
`

It's not clear how useful they are to our APIs, nor how we'd expose them eventually in the Python APIs if we need to. Note these come from the IVI spec.

**Comment by Fladolcetta** [comment]
This is not a supported feature on all drivers. Deferring for now.

**Comment by MrDuff8** [comment]
The CheckAttribute functions exist in the C APIs due to IVI compatibility & legacy use cases. The state model on all of NI's current hardware APIs perform attribute verification as a whole in order to remove ordering dependencies. These functions should not apply.
