### ISSUE TITLE
Several function enums missing from NI-FGEN metadata

### ISSUE THREAD

**Issue by marcoskirsch** [ni/nimi-python#538]
There are functions in NI-FGEN that have parameters of type "enum". I have modified function_addon.py to point to those enums, but they do not actually exist in src/nifgen/metadata/enums.py.

* **ByteOrder** used by **CreateWaveformFromFileF64** and **CreateWaveformFromFileI16**
* **Signal** used by **ExportSignal**
* **RelativeTo** used by **SetNamedWaveformNextWritePosition** and **SetWaveformNextWritePosition**
* **HardwareState** used by **GetHardwareState**
* **Trigger** used by **SendSoftwareEdgeTrigger**

(final names for the enums may be different)

**Comment by marcoskirsch** [comment]
@texasaggie97 is looking into changing the internal process used to extract the initial API metadata. This would include enum information and fix this issue.

**Comment by injaleea** [comment]
Need to enable **test_get_hardware_state** when this fixed

**Comment by bhaswath** [comment]
When adding Triggers enum to the enums_addon.py; making and installing nifgen and running its system tests, I get the following error :

 _______ ERROR collecting src/nifgen/system_tests/test_system_nifgen.py ________
src\nifgen\system_tests\test_system_nifgen.py:1: in <module>
    import nifgen
..\AppData\Local\Programs\Python\Python36-32\lib\site-packages\nifgen\__init__.py:7: in <module>
    from nifgen.session import Session  # noqa: F401
<frozen importlib._bootstrap>:961: in _find_and_load
    ???
<frozen importlib._bootstrap>:950: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:646: in _load_unlocked
    ???
<frozen importlib._bootstrap>:616: in _load_backward_compatible
    ???
..\AppData\Local\Programs\Python\Python36-32\lib\site-packages\_pytest\assertion\rewrite.py:212: in load_module
    py.builtin.exec_(co, mod.__dict__)
..\AppData\Local\Programs\Python\Python36-32\lib\site-packages\nifgen\session.py:2747: in <module>
    class Session(_SessionBase):
..\AppData\Local\Programs\Python\Python36-32\lib\site-packages\nifgen\session.py:2930: in Session
    def configure_digital_edge_script_trigger(self, trigger_id, source, edge=enums.ScriptTriggerDigitalEdgeEdge.RISING):
..\AppData\Local\Programs\Python\Python36-32\lib\enum.py:324: in __getattr__
    raise AttributeError(name) from None
E   AttributeError: RISING
_______ ERROR collecting src/nifgen/system_tests/test_system_nifgen.py ________
src\nifgen\system_tests\test_system_nifgen.py:1: in <module>
    import nifgen
..\AppData\Local\Programs\Python\Python36-32\lib\site-packages\nifgen\__init__.py:7: in <module>
    from nifgen.session import Session  # noqa: F401
<frozen importlib._bootstrap>:961: in _find_and_load
    ???
<frozen importlib._bootstrap>:950: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:646: in _load_unlocked
    ???
<frozen importlib._bootstrap>:616: in _load_backward_compatible
    ???
..\AppData\Local\Programs\Python\Python36-32\lib\site-packages\_pytest\assertion\rewrite.py:212: in load_module
    py.builtin.exec_(co, mod.__dict__)
..\AppData\Local\Programs\Python\Python36-32\lib\site-packages\nifgen\session.py:2747: in <module>
    class Session(_SessionBase):
..\AppData\Local\Programs\Python\Python36-32\lib\site-packages\nifgen\session.py:2930: in Session
    def configure_digital_edge_script_trigger(self, trigger_id, source, edge=enums.ScriptTriggerDigitalEdgeEdge.RISING):
..\AppData\Local\Programs\Python\Python36-32\lib\enum.py:324: in __getattr__
    raise AttributeError(name) from None
E   AttributeError: RISING
!!!!!!!!!!!!!!!!!!! Interrupted: 2 errors during collection !!!!!!!!!!!!!!!!!!!
=========================== 2 error in 1.05 seconds ===========================

**Comment by marcoskirsch** [comment]
> When adding Triggers enum to the enums_addon.py;

Is there a branch on GitHub showing your change so we can try to reproduce?

**Comment by bhaswath** [comment]
Created #622 with this change
