### ISSUE TITLE
Name of function in documentation is incorrectly namespaced

### ISSUE THREAD

**Issue by marcoskirsch** [ni/nimi-python#559]
example:
http://nimi-python.readthedocs.io/en/master/nifgen/functions.html#nifgen.create_arb_sequence
<img width="782" alt="screen shot 2017-11-03 at 7 39 46 am" src="https://user-images.githubusercontent.com/8085768/32374076-4161a3c8-c06a-11e7-98fe-bf413e69b95b.png">

We have:
`nifgen.create_arb_sequence(sequence_length, waveform_handles_array, loop_counts_array)`

I think we should have
`create_arb_sequence(sequence_length, waveform_handles_array, loop_counts_array)`
or
`nifgen.Session.create_arb_sequence(sequence_length, waveform_handles_array, loop_counts_array)`

**Comment by Fladolcetta** [comment]
We should use the following style:

`create_arb_sequence(sequence_length, waveform_handles_array, loop_counts_array)`

If this works.
