### ISSUE TITLE
We should test examples as part of system tests

### ISSUE THREAD

**Issue by marcoskirsch** [ni/nimi-python#563]
Verifying examples work manually (read- we don't accidentally break them) is a hassle. We should integrate them to our nimi-bot testing.

First, the examples should be refactored so that they can be included – add `__name__`, main(), etc. similar to how [nixnet-python](https://github.com/ni/nixnet-python/blob/master/nixnet_examples/can_signal_conversion.py) does it.
(we should do this regardless).

Then we can have a single test file in each examples/ folder (note - this should not make it to documentation, will need filtering) that imports and invokes the examples in a way that they work on simulated device.

**Comment by epage** [comment]
> Then we can have a single test file in each examples/ folder 

What value would you be getting out of this?  Why not have it in with all of the other product tests.

Granted, it has its limitations, but mocking out the driver is also really nice.

For an example of both central example tests and mocked driver, see https://github.com/ni/nixnet-python/blob/master/tests/test_examples.py
