### ISSUE TITLE
Should all optional array input as None ?

### ISSUE THREAD

**Issue by injaleea** [ni/nimi-python#594]
Encountered an error 
```
>       sample_counts_array_ctype = (visatype.ViInt32 * len(sample_counts_array)
)(*sample_counts_array)  # case 4
E       TypeError: object of type 'NoneType' has no len()
```
Its an optional input to method **create_advanced_arb_sequence** with default value None , but some where it is executing a len() for None.

From session.py 
` def create_advanced_arb_sequence(self, waveform_handles_array, loop_counts_array, sample_counts_array=None, marker_location_array=None):`

**Comment by injaleea** [comment]
Noticed there is already an issue opened for the same #593

**Comment by marcoskirsch** [comment]
FYI take a look at #592 because it affects create_advanced_arb_sequence.
