### ISSUE TITLE
Return values of nifgen_GetFIRFilterCoefficients seem to be incorrect

### ISSUE THREAD

**Issue by bhaswath** [ni/nimi-python#596]
While writing the test given below, no matter what value was given to coeff_array, the value returned by session.get_fir_filter_coefficients() is always ([], 95). This is different from the behavior on LabVIEW and seems incorrect.

def test_fir_filter_coefficients():
    with nifgen.Session('', False, 'Simulate=1, DriverSetup=Model:5441;BoardType:PXI') as session:
        coeff_array = [1, 0, -1]
        session.configure_custom_fir_filter_coefficients(coeff_array)
        session.commit()
        array, size = session.get_fir_filter_coefficients()
        assert size == len(coeff_array)

**Comment by marcoskirsch** [comment]
I'm surprised you aren't getting a driver error. On 5441 FIR filter coefficients must be 95 elements and symmetrical. I vaguely remember that the OSP-related attributes aren't looked at unless you enable OSP. Try that.

**Comment by bhaswath** [comment]
Even after enabling OSP, I do not get any error when the FIR Filter coefficients aren't 95 elements and symmetrical. (On LabVIEW as well)

Sorry for not updating this earlier.
