### ISSUE TITLE
Values given for trigger in send_software_trigger() is incorrect in nifgen\session.py

### ISSUE THREAD

**Issue by bhaswath** [ni/nimi-python#597]
The values mentioned in the description for 'trigger' in 'send_software_trigger()' function is incorrect in nifgen\session.py
The values should be 
Start Trigger     1004
Script Trigger    103

But the values given in session.py seem to be of something else:
Args:
            trigger (enums.Trigger): Sets the clock mode of the signal generator.
                ****Defined Values****
                +----------------------------+
                | NIFGEN_VAL_DIVIDE_DOWN     |
                +----------------------------+
                | NIFGEN_VAL_HIGH_RESOLUTION |
                +----------------------------+
                | NIFGEN_VAL_AUTOMATIC       |
                +----------------------------+

**Comment by texasaggie97** [comment]
Internal CAR 677079 filed

**Comment by texasaggie97** [comment]
We now have a "fancy" function with its own documentation so this issue no longer matters.
