### ISSUE TITLE
Self calibration function name is inconsistent across drivers

### ISSUE THREAD

**Issue by marcoskirsch** [ni/nimi-python#615]
```
us-aus-ras-130-164-29-8:nimi-python kirsch$ find generated | grep session\.py | xargs grep -irh "def\ .*self_cal" | sort
    def cal_self_calibrate(self, option):
    def get_self_cal_last_date_and_time(self):
    def get_self_cal_last_date_and_time(self):
    def get_self_cal_last_temp(self):
    def get_self_cal_last_temp(self):
    def get_self_cal_supported(self):
    def get_self_cal_supported(self):
    def self_cal(self):
    def self_cal(self):
```

This can be annoying to the Python customer because I can see iterating over a list of sessions calling things like self_cal. This would break it.

It's not clear whether we want to do it or not, since we are keeping to the C interfaces and inheriting those faults. This falls a little outside of the scope of what we signed up for.

**Comment by texasaggie97** [comment]
This also applies to DCPower self cal
