### ISSUE TITLE
Multiple flake-8 error when following LabVIEW naming convension.

### ISSUE THREAD

**Issue by injaleea** [ni/nimi-python#619]
Created multiple enums for scope form LabVIEW controls , which was not available initially on enums.py . toxing the code throws multiple errors.
```

    'ArrayMeasurement': {
        'values': [
            {
                'name': 'FFT_Amp._Spectrum_(Volts_RMS)',
                'value': 4003,
                'documentation': {
                    'description': 'FFT Amp. Spectrum (Volts RMS)',
                },
            },
        ],
    },
```
**Error : E999 SyntaxError: can't assign to function call**

 ```
   'ClearableMeasurement': {
        'values': [
            {
                'name':'Voltage_Peak-to-Peak',
                'value':5,
            },
            {
                'name':'Volt._Hist._Mean_+_2_Stdev',
                'value':2008,
            },
```
**E226 missing whitespace around arithmetic operator**

How to handle these errors?

**Comment by texasaggie97** [comment]
Don't use LV naming conventions, use C naming convention.

I.e. Instead of `FFT_Amp._Spectrum_(Volts_RMS)` use `NISCOPE_VAL_FFT_AMP_SPECTRUM_VOLTS_RMS`

If you look in niScope.h, you should be able to find `NISCOPE_VAL_`'s for all of these.
