### ISSUE TITLE
Remove i16 flavors of create_waveform and write_waveform methods from NI-FGEN

### ISSUE THREAD

**Issue by marcoskirsch** [ni/nimi-python#632]
NI-FGEN functions that take in waveform as an array of ViUInt16 exist for faster performance and for memory footprint reasons. It requires customers to scale their waveform data to 16-bit signed integers that happen to match the DAC on the devices in order to skip the scaling that the driver would need to perform otherwise.

In Python, right now we have the following create/write waveform functions:

```
    def create_waveform_f64(self, waveform_data_array):
    def create_waveform_from_file_f64(self, file_name, byte_order):
    def create_waveform_from_file_i16(self, file_name, byte_order):
    def create_waveform_i16(self, waveform_data_array):
    def write_binary16_waveform(self, waveform_handle, data):
    def write_named_waveform_f64(self, waveform_name, data):
    def write_named_waveform_i16(self, waveform_name, data):
    def write_waveform(self, waveform_handle, data):
```

The customer who wants ease-of-use will most likely not use ViReal64 / double data. The customer who wants small memory footprint would not get that using a Python list of integers. So there's no point to providing  `create_waveform_i16`, `write_binary16_waveform`, `write_named_waveform_i16`.

For customers who want faster performance and smaller memory footprint in Python, we plan on having "numpy array" flavors of these methods as documented in #511.

Note that we get to keep the "from_file" flavors because the data is not provided as a list.
  
Additionally, we should remove the suffixes that talk about data types since this makes no sense to Python users (what's an f64? what's an i16?).

This leaves us with:

* `create_waveform_f64` -> `create_waveform`
* `create_waveform_from_file_f64` stays the same
* `create_waveform_from_file_i16` stays the same
* ~~`create_waveform_i16`~~
* ~~`write_binary16_waveform`~~
* `write_named_waveform_f64` -> `write_named_waveform`
* ~~`write_named_waveform_i16`~~
* `write_waveform` stays the same

**Comment by texasaggie97** [comment]
I agree with the reasoning. If someone wants performance, use the numpy \*\_from functions, otherwise use a list of floats.
