### ISSUE TITLE
Add intermittent system tests back to NI-SCOPE system tests

### ISSUE THREAD

**Issue by Fladolcetta** [ni/nimi-python#650]
test_configure_trigger_video and test_filter_coefficients caused intermittent test failures. Internal issue report 565504 has been filed to resolve these failures.

We need to re-add this test to complete coverage.

**Comment by MrDuff8** [comment]
NI-SCOPE 19.1 (which should release at some point in H2 2019) should fix this issue. Once we upgrade nimi-bot, we can re-add the test.

**Comment by ni-jfitzger** [comment]
Internal issue 565504 is resolved in the released NI-SCOPE 19.1.1.
