### ISSUE TITLE
niswitch_get_device_info example uses io_resource_descriptor attribute that doesn't exist

### ISSUE THREAD

**Issue by marshallgallatin** [ni/nimi-python#654]
I tried the [niswitch_get_device.py example](https://github.com/ni/nimi-python/blob/master/src/niswitch/examples/niswitch_get_device_info.py) with a PXI-2575, if you use the -d flag it errors:
```
(venv) C:\Users\Administrator\Desktop\niswitch_python_testing>python niswitch_get_device_info.py -n 2575 -d
Device Info:
Traceback (most recent call last):
  File "niswitch_get_device_info.py", line 22, in <module>
    print(row_format.format('Device Name: ', session.io_resource_descriptor))
AttributeError: 'Session' object has no attribute 'io_resource_descriptor'
```
According to [the documentation](http://nimi-python.readthedocs.io/en/master/niswitch/session.html), the io_resource_descriptor attribute doesn't exist.

I'd fix it but I didn't see an appropriate replacement - logical_name isn't the same thing.

python version:
2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]

python -m pip list
enum34 (1.1.6)
niswitch (0.5.0)
pip (9.0.1)
setuptools (38.2.4)
wheel (0.30.0)

Using NI-SWITCH 17.0 on Windows 7 64-bit

**Comment by marcoskirsch** [comment]
Why we need #563

**Comment by marshallgallatin** [comment]
Also specific_driver_revision is in the example but not on the session too

**Comment by Fladolcetta** [comment]
All,

These appears to be removed when @texasaggie97 added attributes_addon. The claim is that these attributes are obsolete, but they are not marked obsolete anywhere else.
