### ISSUE TITLE
niswitch.connect() as Context Manager

### ISSUE THREAD

**Issue by marcoskirsch** [ni/nimi-python#657]
Allows code such as:

with switch_session.connect(channel1, channel2):
    # do some nidmm measurements

When you exit, the connection is automatically opened, even if you exited with an error.

**Comment by MrDuff8** [comment]
Connections in the NI-SWITCH API model outlive the lifetime of the session (by design), so we believe scoping connections like this shouldn't be a first-class citizen of the API.
