### ISSUE TITLE
Improve niscope.Session.fetch()

### ISSUE THREAD

**Issue by marcoskirsch** [ni/nimi-python#663]
In C API, customizing fetch is done by setting some properties. This is hidden and poorly understood. Michael's proposal below makes the API more discoverable and logical. His comments below:

In NI-SCOPE, an obvious example of this is our family of Fetch functions. The prototype for niScope_Fetch is:

```
ViStatus niScope_Fetch(
        ViSession vi,
        ViConstString channelList,
        ViReal64 timeout,
        ViInt32 numSamples,
        ViReal64* wfm,
        struct niScope_wfmInfo* wfmInfo);
```
But, in addition to that, the following attributes all impact what that function does:

* NISCOPE_ATTR_FETCH_RELATIVE_TO
* NISCOPE_ATTR_FETCH_OFFSET
* NISCOPE_ATTR_FETCH_RECORD_NUMBER
* NISCOPE_ATTR_FETCH_NUM_RECORDS     

Beyond not being very easy for users to discover (seriously, our documentation [1] doesn't even mention them), having to change the session state in order to change function behavior makes it very difficult to reason about the code and very easy to introduce subtle bugs that are difficult to track down.
 
The Python API inherited this. The signature of niscope.Session.fetch is:

```
def fetch(self, num_samples, timeout):
```

and users are required to somehow just know to set fetch_num_records in order to fetch more than 1 record from the device.

We can do better than that. A simple improvement would be to do something like:

```
# Defaults to fetching all samples from all records relative to
# pretrigger with a 10 second timeout.

def fetch(self, *kwargs, num_samples=-1, timeout=10.0,
          offset=0, record=0, num_records=-1,
          relative_to=enums.RelativeTo.PRETRIGGER):
```

where the function grabs a lock, saves the state of the fetch attributes, sets the fetch attributes based on the arguments, invokes fetch, and then restores fetch attributes to their prior values before returning. This makes the functionality of fetch more discoverable, and it doesn't change the session state.
 
[ Well, it's not 100% true that it doesn't change the session state because of the read pointer, but I've got a solution for that which I'm omitting for brevity, though I'd be happy to elaborate on it if anyone's interested ].

**Comment by MrDuff8** [comment]
Done.
