### ISSUE TITLE
Remove the measurement library functions from niscope

### ISSUE THREAD

**Issue by Fladolcetta** [ni/nimi-python#667]
There is a large number of functions in NI-SCOPE known as "Measurement Library". They are for analyzing and doing calculations on acquired data.
This set of functions, as it is, are very hard to use in our C API, and extremely un-pythonic in the Python bindings as code-generated.

We believe than rather than expose them as-is, most Python users will rather use any of the excellent Python libraries for analysis (read: [SciPy](https://pypi.python.org/pypi/scipy/1.0.0))

**Comment by texasaggie97** [comment]
We will remove the waveform array measurement functions but leave the scalar measurement functions. This is because scipy does not have anything equivalent.
