### ISSUE TITLE
id_query doesn't do anything so it's confusing

### ISSUE THREAD

**Issue by Fladolcetta** [ni/nimi-python#670]
id_query is currently an optional Boolean parameter on all Session constructors. It doesn't have any effect on our APIs, so it just brings confusion. We should remove it.

**Comment by jayj2510** [comment]
Does this mean that the python apis will be ignoring IVI Spec requirements?

**Comment by texasaggie97** [comment]
There is no IVI spec for Python, so we there isn't anything for us to ignore.

**Comment by jayj2510** [comment]
That's true of LabVIEW as well, but it didn't keep noop functionality out of the LabVIEW APIs.
Not that I dislike this change.
