### ISSUE TITLE
nimodinst does not tell me anything about my pxie6738 card.

### ISSUE THREAD

**Issue by WilyMongooseZero** [ni/nimi-python#758]
It correctly identifies my other cards but does not identify my pxie6738. I have to use the separate nidaqmx module to control this card, when will it get pulled into the modular instruments package?

**Comment by marcoskirsch** [comment]
NI-ModInst API has never supported enumeration of DAQmx devices nor are there plans to add that functionality, irrespective of Python. It supports discovery of NI Modular Instruments and RF devices.

I would tell you to use [NI System Configuration API](http://zone.ni.com/reference/en-XX/help/373107E-01/) but that's not available for Python, unfortunately. I will pass that feedback along.

I'm no DAQmx expert but I believe [this will return a list of all nidaqmx devices in your system](https://nidaqmx-python.readthedocs.io/en/latest/system.html#nidaqmx.system.system.System.devices).
