### ISSUE TITLE
Fgen PXIe 5433 triggering example

### ISSUE THREAD

**Issue by ihouses** [ni/nimi-python#762]
Hello,

I want to use a Fgen PXIe 5433 to generate a trigger when I start the generation in order to synchronise the scope capture with the Fgen generation. I know that FGEN has the capability of generating the trigger so I don't need to use any DAQ card or so.

How can I do that using the FGEN library?

Thanks.

**Comment by marcoskirsch** [comment]
The best place to look for support using NI signal generators is in the [discussion forum](https://forums.ni.com/t5/Signal-Generators/bd-p/310) which is monitored by application engineers and product support engineers. We are not always well equipped to help here, and the issue on the project page are for bugs with the Python APIs.

That said, take a look at [nifgen.Session.export_signal](http://nimi-python.readthedocs.io/en/0.7.0/nifgen/functions.html#nifgen.Session.export_signal).
