### ISSUE TITLE
Additional ease of use wrappers

### ISSUE THREAD

**Issue by texasaggie97** [ni/nimi-python#769]
Yes:
* ~~niscope `read()`~~ #790
* ~~Add channel name to `fetch_multiple()` return~~ #791
* ~~nidcpower `measure_mutliple()`, set None for in_compliance~~ #792
* ~~make private nidcpower advanced sequencing `create_advanced_sequence()`, `create_advanced_sequence_step()`, `delete_advanced_sequence()`,~~ #793
* ~~cal interval functions should return `timedelta()` all APIs~~ #794
* ~~nidcpower `export_signal()` remove `signal_identifier` parameter~~ #795
* ~~Rename niscope `cal_self_cal()` to match others (#615)~~

Possibilities:
* ~~Single function to get cal_date_time with enum~~
* ~~Remove niscope `configure_vertical()` & `configure_chan_characteristics()`~~
* ~~niscope `get_frequency_response()`~~
* ~~niscope single channel, single record `fetch()` (from @auchter)~~

**Comment by Fladolcetta** [comment]
All issues have been completed or assigned to other issues.
