### ISSUE TITLE
nidmm fetch waveform example does not use digit selection.

### ISSUE THREAD

**Issue by WilyMongooseZero** [ni/nimi-python#771]
The digits are collected by the function, but are not actually used to change anything.

`def example(resource_name, options, function, range, digits, points, rate):
    with nidmm.Session(resource_name=resource_name, options=options) as session:
        session.configure_waveform_acquisition(measurement_function=nidmm.Function[function], range=range, rate=rate, waveform_points=points)
        with session.initiate():
            while True:
                time.sleep(0.1)
                backlog, acquisition_state = session.read_status()
                if acquisition_state == nidmm.AcquisitionStatus.FINISHED_WITH_NO_BACKLOG:
                    break
                measurements = session.fetch_waveform(array_size=backlog)
                print(measurements)`

**Comment by marcoskirsch** [comment]
Example in question is:
https://github.com/ni/nimi-python/blob/master/src/nidmm/examples/nidmm_fetch_waveform.py
