### ISSUE TITLE
Anywhere a timedelta is used for parameter, also allow float in seconds

### ISSUE THREAD

**Issue by texasaggie97** [ni/nimi-python#796]
This makes the function call less verbose.
Both will work:
* `fetch(timeout=datetime.timedelta(seconds=1.5))`
* `fetch(timeout=1.5)`

**Comment by Fladolcetta** [comment]
Per discussion we have decided to allow both, this is because we see value in the ease of using a float in seconds and the self documentation of using timedelta.
