### ISSUE TITLE
VI_NULL should be used as the first parameter to GetErrorMessage

### ISSUE THREAD

**Issue by thejcannon** [ni/nimi-python#80]
See [lines 232-235 of session.py](https://github.com/ni/nimi-python/blame/master/generated/nidmm/session.py#L232-L235)

The first parameter to each call of GetErrorMessage should be VI_NULL (or the Python equivalent).
If the session handle is invalid, GetErrorMessage will return a fatal status, which would then be used as the buffer size.

**Comment by Fladolcetta** [comment]
Closed and superseded by issue #154
