### ISSUE TITLE
Add NI-SCOPE Measurement Library support

### ISSUE THREAD

**Issue by Fladolcetta** [ni/nimi-python#806]
All of the measurement library functions are not included because as they are, they would be pythonic.

We should add support for them with pythonic wrappers

**Comment by charterchap** [comment]
Really wanting this one. I'd rather have something that works, than have something "pythonic". I'm looking at http://zone.ni.com/reference/en-XX/help/370592AB-01/digitizers/fetching_scalar_and_array_measurements/ and not seeing a way to do it with nimi-python :(

**Comment by Fladolcetta** [comment]
@charterchap I believe that we marked the measurement library methods private. If you needed measurment library at this time, you might be able to try this out. That being said when we officially support measurement library, your code might break.

Where we mark it as private:
https://github.com/ni/nimi-python/blob/1f193aa260ead422188b8f7a81929bd9c12cce60/src/niscope/metadata/functions_addon.py#L63-L71

The generated file where one of these private functions are defined:
https://github.com/ni/nimi-python/blob/1f193aa260ead422188b8f7a81929bd9c12cce60/generated/niscope/session.py#L1609

**Comment by charterchap** [comment]
It is working more or less. I had to edit session.py in the niscope module on line 2835
```
if type(scalar_meas_function) is not enums.ScalarMeasurement:
            raise TypeError('Parameter mode must be of type ' + str(enums.ScalarMeasurement))
```
to
```
if type(scalar_meas_function) is not enums._ScalarMeasurement:
            raise TypeError('Parameter mode must be of type ' + str(enums._ScalarMeasurement))
```

a quick example for anyone else who comes across this:
`print(session.channels[channels]._fetch_measurement(niscope.enums._ScalarMeasurement.FREQUENCY))`

**Comment by marcoskirsch** [comment]
@texasaggie97 The replacement @charterchap had to do sounds like a small generator bug. I've created #922.
