### ISSUE TITLE
NI-DMM System Tests Fail for Simulated Modules

### ISSUE THREAD

**Issue by Fladolcetta** [ni/nimi-python#82]
"test_take_simple_measurement_works": assumes that nothing is connected (0 Volts). This causes failures on simulated devices which returns simulated data.
"test_warning":  assert false fails.
"test_ViBoolean_attribute": assumes device is not simulated
"test_ViString_attribute": assumes device has a serial number

**Comment by Fladolcetta** [comment]
https://github.com/ni/nimi-python/pull/83

**Comment by texasaggie97** [comment]
Fixed by #83
