### ISSUE TITLE
Makefile unable to handle path with spaces

### ISSUE THREAD

**Issue by hoffiz** [ni/nimi-python#820]
Calling make if you have the nimi-python repo in a location where the path has spaces will result in:

```
makefile:22: C:/Users/jfernand/OneDrive: Permission denied
makefile:22: -: No such file or directory
makefile:22: National: No such file or directory
makefile:22: Instruments/Repositories/nimi-python/build/Makefile: No such file or directory
make: *** No rule to make target `Instruments/Repositories/nimi-python/build/Makefile'.  Stop.
```

I've looked online for solutions and have not be able to find one. I'll keep looking but any suggestion or idea if my environment is missing something will be appreciated. I have followed the non WSL steps and I'm able to build on a virtual machine where I have explicitly avoided spaces in the path to the repo.

**Comment by marcoskirsch** [comment]
Unfortunately this is a limitation of GNU make, and outside of our control short of replacing our whole build system.
