### ISSUE TITLE
make clean is not getting rid of files under generated/

### ISSUE THREAD

**Issue by marcoskirsch** [ni/nimi-python#821]
I ran tox after a long time, before underscores were added in front of some private filenames. GitStatus showed them there. I ran make clean and it didn't get rid of them.

Seems like make clean should delete all of generated/

**Comment by texasaggie97** [comment]
Should `make clean` delete generated? This folder is in GitHub, so should we be deleting it each time?

**Comment by marcoskirsch** [comment]
> This folder is in GitHub, so should we be deleting it each time?

The fact that we put a build artifact in source control makes things strange. We knew it was strange, but decided to do it regardless out of convenience and I think we are still happy with the decision.

> Should make clean delete generated?

That said, it is a build artifact, so i think the answer is yes.
