### ISSUE TITLE
Remove trigger related functions that are configurable through attributes

### ISSUE THREAD

**Issue by marcoskirsch** [ni/nimi-python#827]
Functions such as `nidcpower.Session.configure_digital_edge_measure_trigger(self, input_terminal, edge=enums.DigitalEdge.RISING)` will 90% of the time be called with one argument.

This will set 3 attributes: `measure_trigger_type`, `digital_edge_measure_trigger_input_terminal`, `digital_edge_measure_trigger_edge` (which has a default value in the function).

From [Zen of Python](https://www.python.org/dev/peps/pep-0020/#id3):

> There should be one-- and preferably only one --obvious way to do it.

It may be best to only have one mechanism.

This also applies to other trigger types with similar configure functions such as: `configure_software_edge_measure_trigger`... which at this time is removed from the nidcpower Python API. We should at the very least be consistent in how we approach it.

**Comment by texasaggie97** [comment]
Closed by #872
