### ISSUE TITLE
Build warning Inline interpreted text and error pkg-niscope

### ISSUE THREAD

**Issue by hoffiz** [ni/nimi-python#836]
I'm able to run a build
```
"C:\Program Files\Python27\python" -m tox
```
almost everything runs fine but a warning and a error:

Here is the warning:
**C:\Repositories\nimi-python\docs\niscope\attributes.rst:1416: WARNING: Inline interpreted text or phrase 
reference start-string without end-string.**

and this is the error 

**error: Please correct your package.
ERROR: InvocationError for command 'C:\\Repositories\\nimi-python\\.tox\\64\\pkg-niscope\\Scripts\\python.EXE setup.py check -m -r -s' (exited with code 1)**

This is my summary:
```
27-test: commands succeeded
SKIPPED:  py34-test: InterpreterNotFound: python3.4
SKIPPED:  py35-test: InterpreterNotFound: python3.5
  py36-test: commands succeeded
SKIPPED:  pypy-test: InterpreterNotFound: pypy
SKIPPED:  pypy3-test: InterpreterNotFound: pypy3
  flake8: commands succeeded
  docs: commands succeeded
  pkg-nidmm: commands succeeded
  pkg-nidcpower: commands succeeded
  pkg-nifgen: commands succeeded
ERROR:   pkg-niscope: commands failed
  pkg-niswitch: commands succeeded
  pkg-nimodinst: commands succeeded
```

**Comment by texasaggie97** [comment]
Both the documentation warning and the setup issue should be gone from master now.

They were both cause by some poorly formatted documentation that was fixed earlier.

Please reopen if you are still seeing it.
