### ISSUE TITLE
Documentation tip for repeated capabilities is confusing at best, wrong at worst

### ISSUE THREAD

**Issue by marcoskirsch** [ni/nimi-python#851]
In our generated documentation, any method that has a repeated capability includes [the same blurb](https://github.com/ni/nimi-python/blob/master/build/helper/documentation_snippets.py#L4):

```
This method requires repeated capabilities (usually channels). If called directly on the
nidmm.Session object, then the method will use all repeated capabilities in the session.
You can specify a subset of repeated capabilities using the Python index notation on an
nidmm.Session instance, and calling this method on the result.
```

This is great. Except since #718 we have "containers". Even for channels, we are supposed to use the channel container: `session.channels[2].my_property`.

Given this:

* The blurb is incorrect. We should encourage the use of the container.
* Can we fix the blurb to refer to the appropriate container as appropriate? This may require additional metadata.
```

**Comment by texasaggie97** [comment]
Fixed by #889
