### ISSUE TITLE
Remove defaults for offset/gain/amplitude parameters in all nifgen functions

### ISSUE THREAD

**Issue by marcoskirsch** [ni/nimi-python#865]
> Explicit is better than implicit.
[Zen](https://www.python.org/dev/peps/pep-0020/#id3)

* `configure_freq_list(self, frequency_list_handle, amplitude, dc_offset=0.0, start_phase=0.0)`
* `configure_standard_waveform(self, waveform, amplitude, frequency, dc_offset=0.0, start_phase=0.0)`

Look for other instances.

**Comment by texasaggie97** [comment]
I am not sure what this means. Do you mean remove default values?

**Comment by marcoskirsch** [comment]
> I am not sure what this means. Do you mean remove default values?

Yes, fixed title.

**Comment by texasaggie97** [comment]
How do we determine which parameters get a default value? Should `start_phase` for instance?

**Comment by texasaggie97** [comment]
If we go by
> Explicit is better than implicit.

then nothing would have defaults. I don't think that would be the right thing to do. In the examples you have, I think those defaults are appropriate.

**Comment by texasaggie97** [comment]
The only parameters' default value I think might be questionable are:
* `level` on `configure_trigger_edge()` - default value == 0.0
* `level` on `configure_trigger_hysteresis()` - default value == 0.0
* `hysteresis` on `configure_trigger_hysteresis()` - default value == 0.05

**Comment by marcoskirsch** [comment]
ok
