### ISSUE TITLE
Installation instructions are wrong in documentation

### ISSUE THREAD

**Issue by marcoskirsch** [ni/nimi-python#887]
* Description of issue

Looking at [installation instructions](http://nimi-python.readthedocs.io/en/master/niscope.html#installation) for `niscope`:

```
python -m pip install niscope~=1.0.0.dev0

Collecting niscope~=1.0.0.dev0
  Could not find a version that satisfies the requirement niscope~=1.0.0.dev0 (from versions: 0.5.0, 0.6.0, 0.7.0, 0.8.0.dev0, 0.8.0, 0.9.0)
No matching distribution found for niscope~=1.0.0.dev0
```

1.0.0 is not yet released. But I wonder if this will be a maintenance burden that we should address.

**Comment by texasaggie97** [comment]
This only applies to master. The released readme's are correct. For an example, look at the 0.9.0 readme that is on [PyPI](https://pypi.org/project/nidmm/)

![image](https://user-images.githubusercontent.com/11483903/41061849-a289eeb6-6999-11e8-8bf8-4b70924bdfa0.png)

Do we care about this in master?

**Comment by Fladolcetta** [comment]
Why list the specific version at all?

**Comment by Fladolcetta** [comment]
Closing because Master documentation is pointing to the version of the master trunk that is not released. The documentation on PyPI is correct for the released version.
