### ISSUE TITLE
Contributing link is broken

### ISSUE THREAD

**Issue by marcoskirsch** [ni/nimi-python#888]
* Description of issue

In main page of documentation (http://nimi-python.readthedocs.io/en/master/):

> Contributing
>
> We welcome contributions! You can clone the project repository, build it, and install it by following these instructions.

The words "following these instructions" link to https://github.com/ni/nimi-python/blob/readme-contributing-link/CONTRIBUTING.md which yields a 404 error.

This explains why we aren't getting tens of PRs a day from the community.

**Comment by texasaggie97** [comment]
Fixed with https://github.com/ni/nimi-python/commit/24567821af51486d873f2a7fe5daa8a9831d94f6

Now we will be inundated with PRs, right?
