### ISSUE TITLE
Allow different types from visa type. 

### ISSUE THREAD

**Issue by Fladolcetta** [ni/nimi-python#897]
NI Switch Executive has custom type names. “NISESession” which is equivalent to a “VISession”. Our tools expect to exactly match the types listed in _visatype.py. There should be a way to override this. At this time I manually edited and replaced all type names in functions.py. This might be okay for NI Switch Executive as we could just manually update it since functions or attributes are not regularly added to this API.

**Comment by marcoskirsch** [comment]
Low ROI - although this is internally technically incorrect, there is no customer-facing problem. We will leave it the way it is and only look into fixing when/if nimi-python is expanded to APIs that don't use Visa types.
