### ISSUE TITLE
Printing waveformInfo type fails with AttributeError

### ISSUE THREAD

**Issue by charterchap** [ni/nimi-python#920]
* Printing waveformInfo type fails with AttributeError

* 
 capture a waveform on the scope and print(waveform)

self = <[AttributeError("'WaveformInfo' object has no attribute 'actual_samples'") raised in repr()] WaveformInfo object at 0x2592e92c4e0>

    def __repr__(self):
        return '{0}(absolute_initial_x={1}, relative_initial_x={2}, x_increment={3}, actual_samples={4}, offset={5}, gain={6})'.format(
            self.__class__.__name__, self.absolute_initial_x, self.relative_initial_x, self.x_increment,
>           self.actual_samples, self.offset, self.gain)
E       AttributeError: 'WaveformInfo' object has no attribute 'actual_samples'

C:\Program Files\Python36\lib\site-packages\niscope\waveform_info.py:72: AttributeError

**Comment by Fladolcetta** [comment]
@charterchap 
Have you tried printing the waveform after you index it? Similar to the following:

https://github.com/ni/nimi-python/blob/1f193aa260ead422188b8f7a81929bd9c12cce60/src/niscope/examples/niscope_fetch.py#L19

When I attempted: `print(waveforms)` I got the same error that you did.
Changing to `print(waveforms[0])` caused me to read the waveform infomation.

```
channel             : 0record              : 0Absolute X0         : 0
Relative X0         : -9.99999e-06
dt                  : 2e-08
offset              : 0
gain                : 1wfm length          : 1,000
```

**Comment by charterchap** [comment]
thanks, I see the same with the [0]

**Comment by Fladolcetta** [comment]
> thanks, I see the same with the [0]

Do you mean that you see the same as I do and I should close this issue? 

Or did you mean that you see the same error?

**Comment by charterchap** [comment]
I would close it. I see the same thing. It would be nice if it printed something other than an error. like <list .... WaveformInfo> but i think having this issue will be enough that people can at least search the issue.
