### ISSUE TITLE
A few functions in session.py should be prepended by _

### ISSUE THREAD

**Issue by marcoskirsch** [ni/nimi-python#924]
## Description of issue

Functions such as `get_ctypes_pointer_for_buffer`, `get_ctypes_and_array` are "public". They should not be.
Found this through visual inspection.

**Comment by ni-jfitzger** [comment]
@marcoskirsch I don't think this is a problem anymore, now that we have _library_interpreter.py (where it's now `_get_ctypes_pointer_for_buffer`). I propose we close this.
