### ISSUE TITLE
No Dunder method __version__

### ISSUE THREAD

**Issue by WilyMongooseZero** [ni/nimi-python#928]
* Description of issue

    When using nidmm or any of the other nimi python modules, calling module.__version__ should return the version number of the software. For the purposes of automated system validation, programatically calling the version number to validate that someone has not altered the system is preferred. Additionally, and perhaps more importantly pip installs use the .__version__ method to determine whether the currently installed version is higher or lower than an upgrade version, and without that method, the --force-reinstall operator must be used to update the module.

* Steps to reproduce issue

```
import nidmm
nidmm.__version__
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2878, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-9cc93eb215e9>", line 1, in <module>
    nidmm.__version__
AttributeError: module 'nidmm' has no attribute '__version__'

```
Example of best practice:
```
import requests
requests.__version__
Out[5]: '2.19.1'

 ```

**Comment by marcoskirsch** [comment]
Relevant PEP: https://www.python.org/dev/peps/pep-0396/

Thanks for pointing this out. The only thing I question is the usefulness of returning **only** the module version. I believe the vast majority of customers will want the driver runtime version. I also think a lot of people will be misled if we return only the module version, thinking this is (also?) the driver runtime version.

In the PEP, all the examples return version in the form of `2.19.1`.
Would it be acceptable to return something more complex?
Examples:

* `1.0.1 (NI-SCOPE runtime 18.1)`
* `1.0.1 (NI-SCOPE runtime not installed)`

This would require looking up the version on the installed binary.

**Comment by WilyMongooseZero** [comment]
I don't think so. The version request is specifically to call the python module version. If the module version is version locked to a specific runtime module, then there needs to be some unit test/assertion/error message, or a specific method for calling the installed runtime library to confirm it is installed. The __version__ call is just for standard version checking of the python module only, and is what tells pip which version is higher/better/exact.

I do not know if there are standards around handling seamless pip installs for modules that are version locked to external code. Usually the external code will have specific instructions to use a certain pip version install like: 
`pip install 'nidmm==1.0.0' `
however, without the __version__ method this doesn't work.
