### ISSUE TITLE
Cannot enumerate my devices on Linux

### ISSUE THREAD

**Issue by epage** [ni/nimi-python#939]
Switch and DMM drivers are now available on Linux but not Mod Inst (see [support list](http://www.ni.com/download/ni-linux-device-drivers-2018/7664/en/)).

How do I enumerate my devices on Linux?

**Comment by Fladolcetta** [comment]
Unfortunately at this time, there is not a direct mechanism to list devices in python on Linux.

Workaround:
---

1. In python, open a sub-process
2. Call 'lsni' to list all devices
