### ISSUE TITLE
Contributing.MD is lacking information on tox --scan

### ISSUE THREAD

**Issue by Fladolcetta** [ni/nimi-python#954]
* Description of issue

Instructions in https://github.com/ni/nimi-python/blob/master/CONTRIBUTING.md are unclear regarding the use of forward and backward slashes for tox --scan requirements.

* Steps to reproduce issue
    1. Read https://github.com/ni/nimi-python/blob/master/CONTRIBUTING.md 
    2. Type "C:\Python27\python -m tox --scan C:\Python*\python.exe C:\Python*\python3.exe"
    3. Receive "no previously scanned interpreter names" message
    4. Find out that you should have used forward slashes and used "C:\Python27\python -m tox --scan C:/Python*/python.exe C:/Python*/python3.exe"

**Comment by marcoskirsch** [comment]
no longer applicable
