### ISSUE TITLE
Should SessionBase override `__getitem__` and `__setattr__` to error?

### ISSUE THREAD

**Issue by epage** [ni/nimi-python#955]
This came up in https://github.com/ni/nimi-python/pull/951

Talking to @texasaggie97, it appears that `Session` originally supported these capabilities but they were moved off, so that these error were meant to help people migrate.

If we consider that migration story done, should we drop these?

Why?
- In Python you don't generally override every dunder function to say you don't support it but instead rely on the default behavior
- This might throw off some documentation, analysis tools, and "smart" libraries that check for non-default implementations (ran into this but with a different dunder when using enums)

Instead, the lack of a `getitem` and lack of documentation on `Session` should be sufficient.

**Comment by marcoskirsch** [comment]
I'm on board with the suggestion.
