### ISSUE TITLE
Using temp directory on Linux for python requires sudo, we should update system tests so they can pass on linux

### ISSUE THREAD

**Issue by Fladolcetta** [ni/nimi-python#963]
In our python system tests, we use `gettempdir()`, this directory on Linux requires sudo access to write to it. We should edit our system tests so they can run without elevated access.

https://github.com/ni/nimi-python/blob/a42eefc1826351afc6d86eb84e822e5c410542b6/src/nidmm/system_tests/test_system_nidmm.py#L297

**Comment by MrDuff8** [comment]
This will be high priority when we're regularly running our tests on Linux.

**Comment by marcoskirsch** [comment]
This is not something we observe on `nimibot`. If it was ever an issue, it must have been something specific to @Fladolcetta 's setup.
