### ISSUE TITLE
We should delete the files that we create in our system tests

### ISSUE THREAD

**Issue by Fladolcetta** [ni/nimi-python#964]
In our system tests for import export, we create a new file.

https://github.com/ni/nimi-python/blob/a42eefc1826351afc6d86eb84e822e5c410542b6/src/nidmm/system_tests/test_system_nidmm.py#L294-L305

Nowhere in the code do we delete the created file, we should cleanup files that we no longer need.

**Comment by texasaggie97** [comment]
Closed by #1241
