### ISSUE TITLE
Sequence Step dt property in nidcpower module

### ISSUE THREAD

**Issue by bharathkumarchowdary** [ni/nimi-python#965]
I wanted to set the Sequence Step Delta Time property 
It is important for my use-case, but did not find that in nidcpower module

    OS:
    Name:      Windows
    Version:   10.0.16299
    Bits:      64
    Driver:
    Name:      NI-DCPower
    Version:   18.5.1.49152
    Module:
    Name:      nidcpower
    Version:   1.1.0
    Python:
    Version:   3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 22:20:52) [MSC v.1916 32 bit (Intel)]
    Bits:      32
    Is_Venv:   False
    Installed Packages:
        widgetsnbextension==3.4.2
        webencodings==0.5.1
        wcwidth==0.1.7
        urllib3==1.24.1
        traitlets==4.3.2
        tornado==5.1.1
        testpath==0.4.2
        terminado==0.8.1
        setuptools==40.8.0
        send2trash==1.5.0
        scipy==1.2.1
        retrying==1.3.3
        requests==2.21.0
        regex==2019.2.21
        qtconsole==4.4.3
        pyzmq==18.0.0
        pywinpty==0.5.5
        pyvisa==1.9.1
        pytz==2018.9
        python-dateutil==2.8.0
        pyrsistent==0.14.11
        pygments==2.3.1
        prompt-toolkit==2.0.9
        prometheus-client==0.6.0
        plotly==3.6.1
        pip==19.0.3
        pickleshare==0.7.5
        parso==0.3.4
        pandocfilters==1.4.2
        pandas==0.24.1
        openpyxl==2.6.0
        numpy==1.16.2
        notebook==5.7.4
        nidaqmx==0.5.7
        nbformat==4.4.0
        nbconvert==5.4.1
        mistune==0.8.4
        markupsafe==1.1.1
        jupyter==1.0.0
        jupyter-core==4.4.0
        jupyter-console==6.0.0
        jupyter-client==5.2.4
        jsonschema==3.0.0
        jinja2==2.10
        jedi==0.13.3
        jdcal==1.4
        ipywidgets==7.4.2
        ipython==7.3.0
        ipython-genutils==0.2.0
        ipykernel==5.1.0
        idna==2.8
        et-xmlfile==1.0.1
        entrypoints==0.3
        defusedxml==0.5.0
        decorator==4.3.2
        colorama==0.4.1
        chardet==3.0.4
        certifi==2018.11.29
        bleach==3.1.0
        backcall==0.1.0
        attrs==18.2.0
        titestpy==0.1
        nidcpower==1.1.0
        six==1.12.0

**Comment by texasaggie97** [comment]
This has been added in 1.1.2 version now on PyPI.
