### ISSUE TITLE
could you give examples on the dmm working with switches

### ISSUE THREAD

**Issue by younghang** [ni/nimi-python#975]
I have pxi 4072, tb-2630b and pxi 2530b, and I want to measure voltage from multi channels by python.  But I couldn't find examples of how to get them to work together. The examples are  mianly individual modul. Could you add examples on the dmm working with switches or where can I find references?

**Comment by MrDuff8** [comment]
This is outside of our current scope for our examples. We do have LabVIEW examples for this kind of interaction to use as a reference.
