### ISSUE TITLE
NI-DMM configure_multi_point doesn't set device to continuous acquisition

### ISSUE THREAD

**Issue by liewrichmond** [ni/nimi-python#976]
* Description of issue

    configure_multi_point with trigger or sample count set to 0 doesn't create a continuous acquisition mode for the device. Currently using NI PXIe-4065 hooked up to NI PXIe-1078 Chassis

* `python -c "import nidmm; niscope.print_diagnostic_information()"` 

    ```
    OS:
       Version:   6.1.7601
       Bits:      64
       Name:      Windows
    Driver:
       Version:   18.0.0.49152
       Name:      NI-DMM
    Module:
       Version:   1.1.0
       Name:      nidmm
    Python:
       Version:   2.7.15 |Anaconda, Inc.| (default, Feb 21 2019, 11:55:13) [MSC v.1500 64 bit (AMD64)]
       Bits:      64
       Is_Venv:   False
    ```

* Steps to reproduce issue
``` python
import nidmm
with nidmm.Session("PXI1Slot6") as session:
 session.configure_measurement_digits(measurement_function=nidmm.enums.Function.DC_VOLTS,resolution_digits=6.5,range=-1.0)
 session.configure_multi_point(trigger_count=1, sample_count=0)
 data = session.read_multi_point(1)
 print(data)
```
This doesn't create a loop as expected from http://zone.ni.com/reference/en-XX/help/370384V-01/dmm/continuous/ and as stated in the comments in session.py

**Comment by marcoskirsch** [comment]
See [documentation](https://nimi-python.readthedocs.io/en/latest/nidmm/class.html#read-multi-point).
```
 data = session.read_multi_point(1)
```

You are only reading one point. Instead of `read_multi_point`, use `initiate` and then `fetch` the measurements in a loop.

I will close this since it doesn't appear to be a bug in the nidmm Python module. For support visit https://forums.ni.com/
